"""agentic-rollout-utilization group 3: version-segment bookkeeping (backend-neutral).

* :class:`TokenProvenance` (3.1): per response token, the policy version that
  generated it and its generation log-probability; serialized compactly as
  version segments ``[[version, start, end), ...]`` plus the log-probabilities.
* :func:`cross_version_is` (3.2): the importance-sampling weight of each token
  generated by an older version, ``exp(logp_train - logp_gen)`` truncated to
  ``[clip_low, clip_high]``, with the truncated fraction that is reported
  every round.
* :class:`InFlightTrajectory` / :func:`restore_in_flight` (3.3): the cut's
  "in-flight trajectories" section and what a restore does with it.
* :class:`PolicyAgeGovernor` (3.5): warn when the truncated fraction is high
  and, past the fallback threshold, drop the run's limit to 0 (never back up).
"""

from __future__ import annotations

import math
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass, field
from typing import Any

PROVENANCE_SCHEMA = "yeto-token-provenance-v1"
IN_FLIGHT_SCHEMA = "yeto-in-flight-trajectory-v1"


class ProvenanceError(ValueError):
    pass


# ----------------------------------------------------------------------- 3.1


@dataclass(frozen=True)
class TokenProvenance:
    versions: tuple[int, ...]  # generating policy version per response token
    logprobs: tuple[float, ...]  # generation log-probability per response token

    def __post_init__(self) -> None:
        if len(self.versions) != len(self.logprobs):
            raise ProvenanceError("versions and logprobs must have one entry per token")
        if any(type(v) is not int or v < 0 for v in self.versions):
            raise ProvenanceError("token versions must be non-negative ints")
        if any(not isinstance(p, (int, float)) or isinstance(p, bool) or not math.isfinite(p)
               or p > 0 for p in self.logprobs):
            raise ProvenanceError("log-probabilities must be finite and <= 0")

    def segments(self) -> list[tuple[int, int, int]]:
        """``(version, start, end)`` runs of equal version, in token order."""
        out: list[tuple[int, int, int]] = []
        for i, v in enumerate(self.versions):
            if out and out[-1][0] == v:
                out[-1] = (v, out[-1][1], i + 1)
            else:
                out.append((v, i, i + 1))
        return out

    @property
    def oldest(self) -> int | None:
        return min(self.versions) if self.versions else None

    def to_dict(self) -> dict[str, Any]:
        return {"schema": PROVENANCE_SCHEMA,
                "segments": [list(s) for s in self.segments()],
                "logprobs": [float(p) for p in self.logprobs]}

    @classmethod
    def from_dict(cls, raw: Mapping[str, Any]) -> "TokenProvenance":
        if raw.get("schema") != PROVENANCE_SCHEMA:
            raise ProvenanceError(f"unknown provenance schema {raw.get('schema')!r}")
        versions: list[int] = []
        for seg in raw.get("segments") or ():
            v, start, end = (int(x) for x in seg)
            if start != len(versions) or end <= start:
                raise ProvenanceError("segments must tile the response without gaps")
            versions.extend([v] * (end - start))
        return cls(tuple(versions), tuple(float(p) for p in raw.get("logprobs") or ()))

    def extend(self, version: int, logprobs: Sequence[float]) -> "TokenProvenance":
        """The provenance after a continuation generated by ``version``."""
        return TokenProvenance(self.versions + (int(version),) * len(logprobs),
                               self.logprobs + tuple(float(p) for p in logprobs))


# ----------------------------------------------------------------------- 3.2


@dataclass(frozen=True)
class ISCorrection:
    weights: tuple[float, ...]
    cross_version_tokens: int
    truncated_tokens: int

    @property
    def truncated_fraction(self) -> float | None:
        """Truncated / cross-version tokens; None when no token crossed a version."""
        return (self.truncated_tokens / self.cross_version_tokens
                if self.cross_version_tokens else None)


def cross_version_is(provenance: TokenProvenance, train_logprobs: Sequence[float],
                     current_version: int, *, clip_low: float = 0.0,
                     clip_high: float = 2.0) -> ISCorrection:
    """Per-token weights for training at ``current_version``.

    Tokens generated by ``current_version`` keep weight 1 (on-policy). An older
    token gets ``exp(train - gen)`` truncated into ``[clip_low, clip_high]``;
    a token whose raw ratio lies outside counts as truncated."""
    if len(train_logprobs) != len(provenance.versions):
        raise ProvenanceError("train log-probabilities must cover every response token")
    if not 0.0 <= clip_low <= 1.0 <= clip_high:
        raise ProvenanceError("need 0 <= clip_low <= 1 <= clip_high")
    weights: list[float] = []
    crossed = truncated = 0
    for v, gen, train in zip(provenance.versions, provenance.logprobs, train_logprobs, strict=True):
        if v == current_version:
            weights.append(1.0)
            continue
        if v > current_version:
            raise ProvenanceError(f"token from future version v{v} > v{current_version}")
        crossed += 1
        ratio = math.exp(float(train) - float(gen))
        clipped = min(max(ratio, clip_low), clip_high)
        truncated += clipped != ratio
        weights.append(clipped)
    return ISCorrection(tuple(weights), crossed, truncated)


def batch_truncated_fraction(corrections: Iterable[ISCorrection]) -> float | None:
    crossed = truncated = 0
    for c in corrections:
        crossed += c.cross_version_tokens
        truncated += c.truncated_tokens
    return truncated / crossed if crossed else None


# ----------------------------------------------------------------------- 3.3


@dataclass(frozen=True)
class InFlightTrajectory:
    """One unfinished trajectory carried by a cut (written only under a limit > 0)."""

    trajectory_id: str
    group_id: str
    task_id: str
    provenance: TokenProvenance
    session_ref: str | None = None  # agentic: reference to resumable session state

    def to_dict(self) -> dict[str, Any]:
        return {"schema": IN_FLIGHT_SCHEMA, "trajectory_id": self.trajectory_id,
                "group_id": self.group_id, "task_id": self.task_id,
                "provenance": self.provenance.to_dict(),
                **({"session_ref": self.session_ref} if self.session_ref else {})}

    @classmethod
    def from_dict(cls, raw: Mapping[str, Any]) -> "InFlightTrajectory":
        if raw.get("schema") != IN_FLIGHT_SCHEMA:
            raise ProvenanceError(f"unknown in-flight schema {raw.get('schema')!r}")
        return cls(str(raw["trajectory_id"]), str(raw["group_id"]), str(raw["task_id"]),
                   TokenProvenance.from_dict(raw["provenance"]), raw.get("session_ref"))


@dataclass(frozen=True)
class InFlightRestore:
    resumed: tuple[InFlightTrajectory, ...]
    discarded: tuple[tuple[InFlightTrajectory, str], ...]  # (trajectory, reason)

    def report(self) -> dict[str, Any]:
        reasons: dict[str, int] = {}
        for _t, why in self.discarded:
            reasons[why] = reasons.get(why, 0) + 1
        return {"resumed": len(self.resumed), "discarded": len(self.discarded),
                "discarded_tokens": sum(len(t.provenance.versions) for t, _ in self.discarded),
                "reasons": reasons}


def restore_in_flight(entries: Iterable[Mapping[str, Any] | InFlightTrajectory], *,
                      max_policy_age: int, current_version: int,
                      completed_group_ids: Iterable[str] = ()) -> InFlightRestore:
    """What a restore does with the cut's in-flight section (never an error).

    Limit 0: every entry is discarded and reported. Otherwise an entry resumes
    when its oldest token is within the limit of ``current_version`` and its
    group was not already completed (trained) -- a completed task is never
    used twice."""
    done = set(completed_group_ids)
    resumed: list[InFlightTrajectory] = []
    discarded: list[tuple[InFlightTrajectory, str]] = []
    for raw in entries:
        t = raw if isinstance(raw, InFlightTrajectory) else InFlightTrajectory.from_dict(raw)
        oldest = t.provenance.oldest
        if max_policy_age == 0:
            discarded.append((t, "limit_zero"))
        elif t.group_id in done:
            discarded.append((t, "group_already_completed"))
        elif oldest is not None and current_version - oldest > max_policy_age:
            discarded.append((t, "policy_age_exceeded"))
        else:
            resumed.append(t)
    return InFlightRestore(tuple(resumed), tuple(discarded))


# ----------------------------------------------------------------------- 3.5


@dataclass
class PolicyAgeGovernor:
    """Run-time guard on the cross-version truncated fraction.

    ``warn_fraction``: one warning per round above it. ``fallback_fraction``:
    the effective limit drops to 0 for the rest of the run (only ever down)."""

    limit: int
    warn_fraction: float = 0.2
    fallback_fraction: float = 0.5
    events: list[dict[str, Any]] = field(default_factory=list)

    def __post_init__(self) -> None:
        if not 0.0 <= self.warn_fraction <= self.fallback_fraction <= 1.0:
            raise ProvenanceError("need 0 <= warn_fraction <= fallback_fraction <= 1")
        self.configured = self.limit

    def observe(self, rollout_id: int, truncated_fraction: float | None) -> int:
        """Record one round's fraction; return the effective limit."""
        if truncated_fraction is None or self.limit == 0:
            return self.limit
        if truncated_fraction > self.fallback_fraction:
            self.events.append({"event": "rl_policy_age_fallback", "rollout_id": rollout_id,
                                "truncated_fraction": truncated_fraction,
                                "from_limit": self.limit, "to_limit": 0})
            self.limit = 0
        elif truncated_fraction > self.warn_fraction:
            self.events.append({"event": "rl_policy_age_warning", "rollout_id": rollout_id,
                                "truncated_fraction": truncated_fraction, "limit": self.limit})
        return self.limit
