"""Miles side of the policy-age limit (agentic-rollout-utilization 2.1/2.4).

``SUPPORT``: Miles implements stage 1 (switch and contract) -- limit 0 only
until stage 2 (single-turn carry-over, task 4.1) lands; a larger limit is
refused by the launcher before any machine starts.

:func:`policy_age_argv` derives Miles' own switches from the neutral limit
instead of mapping Miles' boolean ``--partial-rollout`` (design decision 1):
limit 0 emits nothing (default command line unchanged); limit N > 0 emits
``--partial-rollout`` (unfinished groups go back to the buffer and continue
next round) and ``--mask-offpolicy-in-partial-rollout`` (tokens generated by
an older policy are masked out of the loss until the cross-version
importance-sampling correction of task 3.2 replaces the mask).
"""

from __future__ import annotations

from yeto.rl.engine.policy_age import PolicyAgeSupport, validate_limit

SUPPORT = PolicyAgeSupport(backend="miles", stage=1, max_policy_age=0)

PARTIAL_ROLLOUT_FLAGS = ("--partial-rollout", "--mask-offpolicy-in-partial-rollout")


def policy_age_argv(limit: int) -> tuple[str, ...]:
    return PARTIAL_ROLLOUT_FLAGS if validate_limit(limit) > 0 else ()
