"""``RolloutPool`` over upstream InferenceController + RolloutExecutor (task 3.2).

``generate`` runs one upstream training rollout (``prepare_rollout`` then
``rollout_executor.get``) and returns a :class:`RolloutBatchHandle` whose
``payload`` is upstream's ``RolloutDataPack`` (object-store refs; never
dereferenced here). The yeto-visible metadata comes from
:mod:`.rollout_meta_hook`, extracted in the rollout process and delivered via
a small sink. ``require_policy_tokens`` implements the pre-training identity
check (spec: mismatching groups are rejected before training).

E1 membership verbs (rl-infra-spec 3.4, :class:`~..ports.ElasticRolloutPool`)
map yeto member ids (``engine:<cell>``) onto the fork's explicit membership
API (fork M2/M3, michaellchung/miles ``yeto/ports`` 0af62f4d):
``InferenceController.start_cells/stop_cells(expected_epoch)``,
``wait_cells_tracked``, ``drain_cells``/``uncordon_cells``,
``get_membership_status`` and ``restore_membership_state``. Only cells declared
at startup can be started (``declared_cells``); the epoch passed in is the
yeto journal's expected fork epoch (3.3a: the journal is the authority).
"""

from __future__ import annotations

import json
import logging
import math
import time
from collections.abc import Callable
from pathlib import Path
from typing import Any, Protocol
from collections.abc import Mapping
from types import SimpleNamespace

from yeto.rl.engine.ports import GroupMetadata, RolloutBatchHandle, over_sampling_fields
from .traits import MILES_ABORT_MECHANISM
from . import LoopRunner
from .rollout_meta_hook import (
    DEFAULT_SINK_ACTOR,
    METADATA_SCHEMA,
    ROUND_META_SCHEMA,
    put_max_policy_age,
    put_policy_token,
)

logger = logging.getLogger(__name__)


class RolloutMetadataError(RuntimeError):
    """Rollout metadata is missing, malformed or inconsistent with the batch."""


class PolicyTokenMismatch(RuntimeError):
    """Some groups were generated by a policy other than the expected snapshot."""

    def __init__(self, expected: str, groups: tuple[GroupMetadata, ...]) -> None:
        detail = ", ".join(f"{g.group_id}={g.policy_token!r}" for g in groups)
        super().__init__(f"policy token mismatch (expected {expected!r}): {detail}")
        self.expected = expected
        self.groups = groups


def policy_token(rollout_id: int, policy_hash: str) -> str:
    """yeto's policy token (design D3), carried as SGLang weight version.

    Single definition: :attr:`yeto.rl.core.PolicySnapshot.token`.
    """

    from yeto.rl.core import policy_snapshot_token

    return policy_snapshot_token(rollout_id, policy_hash)


# Member id rule lives in the core (decoupling 3.5); same objects re-exported.
from yeto.rl.engine.members import MEMBER_PREFIX, cell_of, member_id  # noqa: E402


def cells_of(members: Any) -> list[str]:
    return sorted(cell_of(m) for m in members)


# Test-only fault injection (rl-infra-spec 3.8 X6 quorum case, gpu-plan-v2 A5):
# sleep this many seconds before the FIRST fork ``start_cells`` of the process.
# Unset (default) = no effect. Set by the launcher's
# ``--rl-test-inject-start-delay-s`` (exported in the island run command).
INJECT_START_DELAY_ENV = "YETO_RL_TEST_INJECT_START_DELAY_S"
# Test-only (plan.md E1-D ③④, 3.7): the next N fork ``stop_cells`` calls fail
# inside the fork AFTER deregistration (its engine provider's stop raises), so
# the fork records ``incomplete``. Unset (default) = no effect.
INJECT_STOP_FAILURES_ENV = "YETO_RL_TEST_INJECT_STOP_FAILURES"
# Test-only (A4b): during the FIRST drain of the process an artificial tool-wait
# entry is put on the ToolWaitBoard and removed again after this many seconds. Longer
# than the drain budget it makes the drain time out -> CANCELLED -> undrain, with no
# request touched (the entry is not a request). Unset (default) = no effect.
INJECT_TOOL_WAIT_ENV = "YETO_RL_TEST_INJECT_TOOL_WAIT_S"
# Test-only (A4b / E1-C variant): the next N ``undrain`` calls fail inside the
# adapter (as a fork uncordon failure would), so a drain timeout cannot restore
# the old routing and the controller must end in RECOVERY_REQUIRED, never CANCELLED.
INJECT_UNDRAIN_FAIL_ENV = "YETO_RL_TEST_INJECT_UNDRAIN_FAIL"
INJECTED_TOOL_WAIT_ID = "yeto-test-injected-tool-wait"
# Test-only (A4bc / 3.3 X5 "no replay"): when set (any non-empty value; "1"
# from the launcher), every execution of the injected tool is journaled in
# ``<elastic state dir>/side_effects.jsonl`` (tool_wait.ToolSideEffectLog):
# one ``tool_side_effect`` record *before* the tool wait starts, keyed by
# (trajectory_id, tool_call_id). The judge requires exactly one record per
# pair and none after the cancelled transaction's CANCELLED phase.
SIDE_EFFECT_LOG_ENV = "YETO_RL_TEST_TOOL_SIDE_EFFECT_LOG"
SIDE_EFFECT_LOG_FILE = "side_effects.jsonl"


def side_effect_log_enabled(environ: Any = None) -> bool:
    import os

    raw = (os.environ if environ is None else environ).get(SIDE_EFFECT_LOG_ENV)
    return bool(raw) and str(raw).strip().lower() not in ("0", "false", "no", "off")


def injected_tool_call_id(members: frozenset[str]) -> str:
    """Deterministic tool-call id of the injected tool for one drain of ``members``:
    a replayed drain of the same members yields the *same* id (journaled twice =
    replay), a drain of other members a different one."""
    return f"{INJECTED_TOOL_WAIT_ID}:drain:{','.join(sorted(members))}"


def injected_start_delay(environ: Any = None) -> float | None:
    import os

    raw = (os.environ if environ is None else environ).get(INJECT_START_DELAY_ENV)
    if raw in (None, ""):
        return None
    value = float(raw)
    if not value > 0:
        raise ValueError(f"{INJECT_START_DELAY_ENV} must be a positive number of seconds")
    return value


def read_executor_cursor(executor: Any) -> tuple[dict[str, int] | None, int | None]:
    """Runs INSIDE the rollout executor actor (``__ray_call__``): its data
    source's current cursor and buffer length (rollout_meta_hook rules)."""
    from .rollout_meta_hook import data_cursor as read_cursor

    return read_cursor(getattr(executor, "data_source", None))


def seek_executor_cursor(executor: Any, cursor: Mapping[str, int]) -> dict[str, int] | None:
    """Runs INSIDE the rollout executor actor (``__ray_call__``): move its data
    source to ``cursor`` the way Miles' ``RolloutDataSource.load`` would (the
    same four fields; re-shuffle for the cursor's epoch when the source
    shuffles per epoch) and return the cursor it reports afterwards."""
    from .rollout_meta_hook import _CURSOR_FIELDS
    from .rollout_meta_hook import data_cursor as read_cursor

    source = getattr(executor, "data_source", None)
    source = getattr(source, "__self__", source)
    if source is None:
        raise RuntimeError("data cursor seek: the rollout executor has no data_source")
    missing = [f for f in _CURSOR_FIELDS if f not in cursor]
    if missing:
        raise RuntimeError(f"data cursor seek: cursor lacks {missing}")
    previous_epoch = getattr(source, "epoch_id", None)
    for name in _CURSOR_FIELDS:
        setattr(source, name, int(cursor[name]))
    args = getattr(source, "args", None)
    dataset = getattr(source, "dataset", None)
    if (dataset is not None and getattr(args, "rollout_shuffle", False)
            and int(cursor["epoch_id"]) != previous_epoch):
        dataset.shuffle(int(cursor["epoch_id"]))
    return read_cursor(source)[0]


def arm_stop_failure_in_controller(controller: Any) -> str:
    """Runs INSIDE the fork InferenceController actor (``__ray_call__``), test only
    (E1-D ③④): the engine provider's next ``stop_cells`` raises once, so the fork
    takes its real half-failure path (membership ``incomplete``, reason
    ``stop_failed``). Returns the provider class name as the arming receipt."""
    provider = getattr(controller, "_engine_provider", None)
    if provider is None:
        raise RuntimeError("stop failure injection: the fork controller has no _engine_provider")
    real = provider.stop_cells

    async def failing_stop(*args: Any, **kwargs: Any) -> Any:
        provider.stop_cells = real  # one shot
        import sys

        print("[yeto] TEST INJECTION YETO_RL_TEST_INJECT_STOP_FAILURES: provider stop_cells fails "
              "(inside the fork controller actor)", file=sys.stderr, flush=True)
        raise RuntimeError("injected provider stop failure (test)")

    provider.stop_cells = failing_stop
    return type(provider).__name__


def _is_ray_handle(obj: Any) -> bool:
    return type(obj).__name__ == "ActorHandle"


def _executor_target(executor: Any) -> tuple[str, Any]:
    """("ray", actor handle) | ("local", data source) | ("unknown", None).

    Only instance attributes are looked at: Miles' ``RayWorkerHandle.__getattr__``
    answers ANY name (``data_source`` included) with a remote-call coroutine."""
    attrs = getattr(executor, "__dict__", None) or {}
    inner = attrs.get("_actor_handle")
    if inner is not None:  # miles.utils.workers.ray_worker_handle.RayWorkerHandle
        return "ray", inner
    if _is_ray_handle(executor):
        return "ray", executor
    source = attrs.get("data_source")
    if source is not None:
        return "local", source
    return "unknown", None


async def _awaited(value: Any) -> Any:
    return await value if hasattr(value, "__await__") else value


class MembershipPlanError(RuntimeError):
    """The pool cannot provide the requested engines."""


async def running_members(controller: Any) -> frozenset[str]:
    """Rollout members = cells the controller reports ``Running``.

    Shared by ``MilesRolloutPool.members`` and ``MilesPublisher`` so both
    sides of the driver's acknowledgement check use one source.
    """

    statuses = await controller.get_cell_statuses() or {}
    return frozenset(
        member_id(cell_id)
        for cell_id, status in statuses.items()
        if getattr(status, "phase", None) == "Running"
    )


def require_policy_tokens(batch: RolloutBatchHandle, expected_token: str) -> None:
    # A group carrying version segments (limit > 0, 4.1) names its oldest version;
    # the driver checked it against the policy-age window before training.
    bad = tuple(g for g in batch.mismatched_groups(expected_token) if not g.policy_versions)
    if bad:
        raise PolicyTokenMismatch(expected_token, bad)


class MetadataSource(Protocol):
    def take(self, rollout_id: int) -> dict[str, Any]: ...


# --------------------------------------------------------------------------
# Sinks readable from the driver
# --------------------------------------------------------------------------


class DirMetadataSource:
    """Reads the ``dir:`` sink; the file is consumed (deleted) once read."""

    def __init__(self, directory: str | Path) -> None:
        self.directory = Path(directory)

    @property
    def sink_spec(self) -> str:
        return f"dir:{self.directory}"

    def set_policy_token(self, token: str) -> None:
        put_policy_token(token, self.sink_spec)

    def set_max_policy_age(self, limit: int) -> None:
        put_max_policy_age(limit, self.sink_spec)

    def take(self, rollout_id: int) -> dict[str, Any]:
        for name in (f"rollout-{rollout_id}.json", "rollout-latest.json"):
            path = self.directory / name
            if path.exists():
                payload = json.loads(path.read_text(encoding="utf-8"))
                path.unlink()
                extra = []
                round_path = self.directory / f"round-{rollout_id}.json"
                if round_path.exists():
                    extra.append(json.loads(round_path.read_text(encoding="utf-8")))
                    round_path.unlink()
                return merge_round_metadata(payload, extra, rollout_id)
        raise RolloutMetadataError(f"no rollout metadata for rollout {rollout_id} in {self.directory}")


def merge_round_metadata(
    payload: dict[str, Any], records: list[dict[str, Any]], rollout_id: int
) -> dict[str, Any]:
    """Attach per-round counters reported after the all-samples hook (same rollout only)."""

    merged = dict(payload)
    for record in records:
        if record.get("rollout_id") != rollout_id:
            raise RolloutMetadataError(
                f"per-round metadata for rollout {record.get('rollout_id')} "
                f"arrived with rollout {rollout_id}"
            )
        for key, value in record.items():
            if key in ("schema", "rollout_id"):
                continue
            if key in merged:
                raise RolloutMetadataError(f"per-round metadata {key} reported twice")
            merged[key] = value
    return merged


def _sink_actor_class():
    import ray

    @ray.remote(num_cpus=0)
    class _YetoRolloutMetaSink:
        def __init__(self) -> None:
            self._pending: list[str] = []
            self._token: str | None = None

        def set_token(self, token: str) -> None:
            self._token = token

        def get_token(self) -> str | None:
            return self._token

        # agentic-rollout-utilization 3.5/4.1: the run's policy-age limit after a
        # governor fallback (None = the configured limit; only ever lowered).
        def set_limit(self, limit: int) -> None:
            self._limit = int(limit)

        def get_limit(self) -> int | None:
            return getattr(self, "_limit", None)

        def put(self, encoded: str) -> None:
            self._pending.append(encoded)

        def take_all(self) -> list[str]:
            items, self._pending = self._pending, []
            return items

    return _YetoRolloutMetaSink


class RayMetadataSink:
    """Named Ray actor that rollout-process hooks push metadata into."""

    def __init__(self, name: str = DEFAULT_SINK_ACTOR, *, timeout_s: float = 30.0) -> None:
        import ray

        self.name = name
        self.timeout_s = timeout_s
        self._ray = ray
        self._actor = _sink_actor_class().options(name=name, get_if_exists=True).remote()

    @property
    def sink_spec(self) -> str:
        return f"ray:{self.name}"

    def set_policy_token(self, token: str) -> None:
        self._ray.get(self._actor.set_token.remote(token))

    def set_max_policy_age(self, limit: int) -> None:
        self._ray.get(self._actor.set_limit.remote(int(limit)))

    def take(self, rollout_id: int) -> dict[str, Any]:
        deadline = time.monotonic() + self.timeout_s
        while True:
            items = [json.loads(i) for i in self._ray.get(self._actor.take_all.remote())]
            main = [i for i in items if i.get("schema") != ROUND_META_SCHEMA]
            extra = [i for i in items if i.get("schema") == ROUND_META_SCHEMA]
            if items:
                if len(main) != 1:
                    raise RolloutMetadataError(
                        f"expected one metadata record for rollout {rollout_id}, got {len(main)}"
                    )
                return merge_round_metadata(main[0], extra, rollout_id)
            if time.monotonic() > deadline:
                raise RolloutMetadataError(f"no rollout metadata for rollout {rollout_id}")
            time.sleep(0.05)


# --------------------------------------------------------------------------
# Handle construction
# --------------------------------------------------------------------------


def _number(value: Any) -> float:
    return math.nan if value is None else float(value)


def handle_from_metadata(
    payload: dict[str, Any],
    *,
    rollout_id: int,
    policy_version: int,
    policy_hash: str,
    data_pack: Any,
) -> RolloutBatchHandle:
    if not isinstance(payload, dict) or payload.get("schema") != METADATA_SCHEMA:
        raise RolloutMetadataError(f"malformed rollout metadata: {payload!r:.200}")
    reported = payload.get("rollout_id")
    if reported is not None and reported != rollout_id:
        raise RolloutMetadataError(f"metadata is for rollout {reported}, expected {rollout_id}")
    groups = tuple(
        GroupMetadata(
            group_id=str(g["group_id"]),
            sample_ids=tuple(str(s) for s in g["sample_ids"]),
            policy_token=str(g["policy_token"]),
            reward_mean=_number(g["reward_mean"]),
            reward_std=_number(g["reward_std"]),
            token_count=int(g["token_count"]),
            filtered_samples=(
                int(g["filtered_samples"]) if g.get("filtered_samples") is not None else None
            ),
            # 4.1: version segments of a carried-over group (limit > 0 only)
            policy_versions=(
                tuple(int(v) for v in g["policy_versions"]) if g.get("policy_versions") else None
            ),
        )
        for g in payload["groups"]
    )
    if not groups:
        raise RolloutMetadataError(f"rollout {rollout_id} produced no trained groups")
    indices = getattr(data_pack, "sample_indices", None)
    if indices is not None:
        expected = sorted(int(i) for i in payload.get("trained_sample_indices", ()))
        if sorted(int(i) for i in indices) != expected:
            raise RolloutMetadataError(
                f"rollout {rollout_id}: metadata samples do not match the training batch"
            )
    return RolloutBatchHandle(
        rollout_id=rollout_id,
        policy_version=policy_version,
        policy_hash=policy_hash,
        groups=groups,
        completed=int(payload["completed"]),
        aborted=int(payload["aborted"]),
        payload=data_pack,
        # rollout_meta_hook: trained-group filter drops (terminal). Carried-over
        # leftovers (cut-audit §3): the ports path forbids partial rollout, so the
        # only reuse is the data buffer; a reported empty buffer means 0.
        filtered=int(payload["filtered"]) if "filtered" in payload else None,
        # Limit > 0 (agentic-rollout-utilization 4.1): partial rollout puts the
        # groups not completed back into the buffer; their count is reported.
        carried_over=(int(payload["carried_out_groups"]) if "carried_out_groups" in payload
                      else 0 if payload.get("buffer_length") == 0 else None),
        data_cursor=payload.get("data_cursor"),
        buffer_length=payload.get("buffer_length"),
        submitted_groups=payload.get("submitted_groups"),
        aborted_in_flight_groups=payload.get("aborted_in_flight_groups"),
        aborted_in_flight_trajectories=payload.get("aborted_in_flight_trajectories"),
        aborted_in_flight_tokens=payload.get("aborted_in_flight_tokens"),
        aborted_in_flight_unknown_groups=payload.get("aborted_in_flight_unknown_groups"),
        abort_mechanism=MILES_ABORT_MECHANISM,
        tool_wait_seconds=(
            float(payload["tool_wait_seconds"]) if "tool_wait_seconds" in payload else None
        ),
        nonzero_advantages=(
            int(payload["nonzero_advantages"]) if "nonzero_advantages" in payload else None
        ),
        policy_age_violation=(
            int(payload["policy_age_violation"]) if "policy_age_violation" in payload else None
        ),
        batch_summary=payload.get("batch_summary"),
        batch_summary_by_bucket=payload.get("batch_summary_by_bucket"),
        tito_session_mismatch_records=(
            tuple(payload["tito_session_mismatch_records"])
            if payload.get("tito_session_mismatch_records") else None
        ),
        trajectory_rewards=(
            tuple(payload["trajectory_rewards"]) if payload.get("trajectory_rewards") else None
        ),
        carry_over=_carry_over_fields(payload),
        cross_version_truncated_fraction=(
            float(payload["cross_version_truncated_fraction"])
            if payload.get("cross_version_truncated_fraction") is not None else None
        ),
        over_sampling=over_sampling_fields(payload.get("over_sampling")),
    )


_CARRY_OVER_KEYS = (
    "max_policy_age", "carried_out_groups", "cross_version_tokens", "trained_response_tokens",
    "cross_version_scored_tokens", "cross_version_unscored_samples",
    # 5.5: distribution of the cross-version IS ratio (calibrates warn/fallback)
    "cross_version_ratio_p50", "cross_version_ratio_p90", "cross_version_ratio_p99",
    "cross_version_ratio_min", "cross_version_ratio_max",
    "cross_version_unscored_reasons", "cross_version_unknown_version_tokens",
    "cross_version_ratio_near_zero", "cross_version_ratio_near_zero_examples",
    # 5.1/5.3: agentic suspension between model turns (carry_over.suspend_fields)
    "suspended_groups", "suspended_done_groups", "over_age_cancelled_groups",
    "over_age_cancelled_samples", "over_age_cancelled_tokens", "over_age_unknown_groups",
    "resumed_groups", "resumed_done_groups", "suspend_expired_trajectories",
    "policy_age_exceeded_trajectories", "suspended_trajectories", "suspended_env_seconds",
    "suspend_retried_turns",
)


def _carry_over_fields(payload: dict[str, Any]) -> dict[str, Any] | None:
    """4.1: the carry-over accounting of a limit > 0 rollout (None at limit 0)."""
    if not payload.get("max_policy_age"):
        return None
    from .carry_over import CARRY_FIELDS

    return {k: payload[k] for k in (*_CARRY_OVER_KEYS, *CARRY_FIELDS) if k in payload}


def _http_get_json(url: str, timeout_s: float = 2.0) -> Any:
    import urllib.request

    with urllib.request.urlopen(url, timeout=timeout_s) as response:  # noqa: S310 - router URL
        return json.loads(response.read().decode("utf-8"))


# 1.7 load attribution: what the tool-wait count is when no board is wired.
# ``stock``: Miles' own generate (no custom generate function) makes no tool
# calls, so 0 is known; any other custom generate without a board is unknown.
TOOL_WAIT_NO_BOARD_STOCK = "stock-generate"
# IR-2: the island runs no agent harness (no custom agent function): harness
# counts are known zeros (tool_wait.HARNESS_ZERO), never "unknown".
HARNESS_NOT_AGENTIC = "not-agentic"


def _engine_load(entries: Any) -> tuple[int, int] | None:
    """SGLang ``/get_load`` (one entry per DP rank) -> (running, waiting)."""
    if not isinstance(entries, list) or not entries:
        return None
    running = waiting = 0
    for entry in entries:
        if not isinstance(entry, dict) or "num_reqs" not in entry or "num_waiting_reqs" not in entry:
            return None
        total, queued = int(entry["num_reqs"]), int(entry["num_waiting_reqs"])
        running += total - queued
        waiting += queued
    return running, waiting


def _engine_kv_used(entries: Any) -> int | None:
    """agentic-rollout-utilization 1.3: KV tokens in use, SGLang ``/get_load``
    (``num_tokens - num_pending_tokens`` = the scheduler's ``num_used_tokens``,
    summed over DP ranks). None when an older engine omits the fields."""
    if not isinstance(entries, list) or not entries:
        return None
    used = 0
    for entry in entries:
        if not isinstance(entry, dict):
            return None
        total, pending = entry.get("num_tokens"), entry.get("num_pending_tokens")
        if type(total) is not int or type(pending) is not int:
            return None
        used += total - pending
    return used


def _engine_kv_capacity(info: Any) -> int | None:
    """SGLang ``/server_info`` ``internal_states[*].memory_usage.token_capacity`` (sum)."""
    if not isinstance(info, dict):
        return None
    states = info.get("internal_states")
    if not isinstance(states, list) or not states:
        return None
    values = [(s.get("memory_usage") or {}).get("token_capacity") if isinstance(s, dict) else None
              for s in states]
    if all(type(v) is int and v > 0 for v in values):
        return int(sum(values))
    return None


def _engine_capacity(info: Any) -> int | None:
    """SGLang ``/server_info``: concurrent requests the engine admits (sum over DP ranks)."""
    if not isinstance(info, dict):
        return None
    states = info.get("internal_states")
    if isinstance(states, list) and states:
        values = [s.get("effective_max_running_requests_per_dp") for s in states
                  if isinstance(s, dict)]
        if values and all(isinstance(v, int) and v > 0 for v in values):
            return int(sum(values))
    value = info.get("max_running_requests")
    return int(value) if isinstance(value, int) and value > 0 else None


class MilesRolloutPool:
    """``RolloutPool`` port. ``expected_policy`` returns the published (version, hash)."""

    def __init__(
        self,
        *,
        inference_controller: Any,
        rollout_executor: Any,
        metadata: MetadataSource,
        expected_policy: Callable[[], tuple[int, str]],
        runner: LoopRunner | None = None,
        args: Any = None,
        declared_cells: Any = None,
        track_timeout_s: float = 600.0,
        tool_wait_board: Any = None,
        worker_manager: Any = None,
        bundles: Any = None,
        gpus_per_engine: int | None = None,
        load_tool_wait: Any = None,
        harness: Any = None,
        side_effect_log: Any = None,
    ) -> None:
        # 3.3 X5 evidence: tool_wait.ToolSideEffectLog (or its path); None = off.
        if side_effect_log is not None and not hasattr(side_effect_log, "record"):
            from yeto.rl.engine.tool_wait import ToolSideEffectLog

            side_effect_log = ToolSideEffectLog(side_effect_log)
        self._side_effects = side_effect_log
        # rl-infra-spec 1.7 ToolWaitBoard (local or actor handle); None = no
        # tool-wait count, so trajectory_load() is unknown (None).
        self._tool_wait_board = tool_wait_board
        # IR-2: harness board (tool_wait.HarnessBoard, local or actor handle),
        # HARNESS_NOT_AGENTIC for islands without a harness (explicit zeros),
        # or None = unknown (fails the drain closed).
        self._harness = harness
        # 1.7 load samples read tool waits from ``load_tool_wait`` (a board,
        # TOOL_WAIT_NO_BOARD_STOCK, or None = unknown); default: the drain board.
        self._load_tool_wait = load_tool_wait if load_tool_wait is not None else tool_wait_board
        self._capacity: dict[str, int] = {}
        self._kv_capacity: dict[str, int] = {}
        self._args = args
        # Cells the fork declared at startup (M1 bundles); None = E1 verbs off.
        self._declared = None if declared_cells is None else tuple(str(c) for c in declared_cells)
        self._track_timeout_s = float(track_timeout_s)
        self._controller = inference_controller
        self._executor = rollout_executor
        self._metadata = metadata
        self._expected_policy = expected_policy
        self._run = (runner or LoopRunner()).run
        self._last_cursor: dict[str, int] | None = None
        # test-only start delay (INJECT_START_DELAY_ENV); applied once per process
        self._inject_start_delay = injected_start_delay()
        self.injected_start_delays: list[float] = []
        self._sleep = time.sleep
        import os

        self._stop_failures_left = int(os.environ.get(INJECT_STOP_FAILURES_ENV) or 0)
        if self._stop_failures_left < 0:
            raise ValueError(f"{INJECT_STOP_FAILURES_ENV} must be >= 0")
        self.injected_stop_failures = 0
        raw_uf = os.environ.get(INJECT_UNDRAIN_FAIL_ENV)
        self._inject_undrain_fail = int(raw_uf) if raw_uf else 0
        self.injected_undrain_failures: list[frozenset[str]] = []
        raw_tw = os.environ.get(INJECT_TOOL_WAIT_ENV)
        self._inject_tool_wait = float(raw_tw) if raw_tw else None
        if self._inject_tool_wait is not None and not self._inject_tool_wait > 0:
            raise ValueError(f"{INJECT_TOOL_WAIT_ENV} must be a positive number of seconds")
        self.injected_tool_waits: list[float] = []
        self.event_sink: Callable[..., None] | None = None  # test_injection record sink
        # E3 role transfer (4.7): fork RayWorkerManager handle (None = the named
        # actor, looked up on first use), the startup bundle map
        # (bundles.StartupBundles: pool GPU ids <-> startup PG bundles) and
        # GPUs per engine.
        self._worker_manager = worker_manager
        self._bundles = bundles
        self._gpus_per_engine = gpus_per_engine
        self._bind_seq = 0

    def set_max_policy_age(self, limit: int) -> None:
        """3.5 governor fallback (driver optional verb): lower the rollout side's
        policy-age limit; the buffer filter then keeps only current complete
        groups (limit-0 rule) and the metadata stops carrying version segments."""
        setter = getattr(self._metadata, "set_max_policy_age", None)
        if not callable(setter):
            raise RuntimeError("this rollout metadata sink cannot lower the policy-age limit")
        setter(int(limit))

    def live_data_cursor(self) -> tuple[dict[str, int] | None, int | None]:
        """The data source position NOW (and its reuse-buffer length), read inside
        the rollout executor's process -- not the last batch's cached value.
        Catches a cursor moved outside generation (``rollout_executor.load``
        during a trainer rebuild; E2 G-4.5 row 5).

        Miles (fork e3a11ab3) hands the driver a ``RayWorkerHandle`` whose
        ``__getattr__`` turns every name into a remote method call; the Ray
        actor handle is its ``_actor_handle``. The read runs in that actor via
        Ray's ``__ray_call__`` (``read_executor_cursor``). A bare Ray
        ``ActorHandle`` is used the same way; a local executor object is read
        directly. Anything else, or any failure: ``(None, None)`` = unknown
        (logged with the reason) -- never the cached value."""
        from .rollout_meta_hook import data_cursor as read_cursor

        kind, target = _executor_target(self._executor)
        if kind == "local":
            try:
                return read_cursor(target)
            except Exception as exc:  # noqa: BLE001 - unknown
                logger.warning("live data cursor: local read failed: %r", exc)
                return None, None
        if kind != "ray":
            logger.warning("live data cursor unknown: rollout executor %s is neither a local "
                           "executor nor a Ray actor (handle)", type(self._executor).__name__)
            return None, None
        remote = getattr(getattr(target, "__ray_call__", None), "remote", None)
        if not callable(remote):
            logger.warning("live data cursor unknown: Ray actor handle %s has no __ray_call__",
                           type(target).__name__)
            return None, None
        try:
            cursor, length = self._run(_awaited(remote(read_executor_cursor)))
        except Exception as exc:  # noqa: BLE001 - unknown
            logger.warning("live data cursor unknown: __ray_call__ in the executor actor "
                           "failed: %r", exc)
            return None, None
        if cursor is None:
            logger.warning("live data cursor unknown: the executor's data source reports no "
                           "complete cursor")
        return (None if cursor is None else dict(cursor)), length

    def seek_data_cursor(self, cursor: Mapping[str, int]) -> dict[str, int] | None:
        """Restart (driver ``_restore_data_cursor``): move the executor's data
        source to the ledger's restart cursor, inside the executor's process
        (same targets as ``live_data_cursor``); returns the cursor read back
        there, None = unknown (the driver then refuses to train)."""
        wanted = {k: int(v) for k, v in dict(cursor).items()}
        kind, target = _executor_target(self._executor)
        if kind == "local":
            return seek_executor_cursor(SimpleNamespace(data_source=target), wanted)
        if kind != "ray":
            raise RuntimeError("data cursor seek: rollout executor %s is neither a local "
                               "executor nor a Ray actor (handle)" % type(self._executor).__name__)
        remote = getattr(getattr(target, "__ray_call__", None), "remote", None)
        if not callable(remote):
            raise RuntimeError("data cursor seek: Ray actor handle %s has no __ray_call__"
                               % type(target).__name__)
        landed = self._run(_awaited(remote(seek_executor_cursor, wanted)))
        self._last_cursor = None if landed is None else dict(landed)
        return None if landed is None else dict(landed)

    def _in_executor(self, fn: Any, *fn_args: Any, **fn_kwargs: Any) -> Any:
        """Run ``fn(executor, ...)`` inside the rollout executor's process (same
        targets as ``live_data_cursor``); raises when it cannot."""
        kind, target = _executor_target(self._executor)
        if kind == "local":
            return fn(SimpleNamespace(data_source=target), *fn_args, **fn_kwargs)
        if kind != "ray":
            raise RuntimeError("rollout executor %s is neither a local executor nor a Ray "
                               "actor (handle)" % type(self._executor).__name__)
        remote = getattr(getattr(target, "__ray_call__", None), "remote", None)
        if not callable(remote):
            raise RuntimeError("Ray actor handle %s has no __ray_call__" % type(target).__name__)
        return self._run(_awaited(remote(fn, *fn_args, **fn_kwargs)))

    def export_in_flight(self) -> dict[str, Any]:
        """agentic-rollout-utilization 3.3 (limit > 0): the cut's in-flight
        entries (buffered groups, suspended agentic trajectories); raises when
        they cannot be read (the cut is then refused, never written without them)."""
        from .in_flight import export_in_flight

        return dict(self._in_executor(export_in_flight))

    def import_in_flight(self, entries: Any, *, max_policy_age: int, current_version: int,
                         completed_group_ids: Any = ()) -> dict[str, Any]:
        """Restore: continue or discard the cut's in-flight entries (report)."""
        from .in_flight import import_in_flight

        return dict(self._in_executor(
            import_in_flight, list(entries), max_policy_age=int(max_policy_age),
            current_version=int(current_version), completed_group_ids=list(completed_group_ids)))

    def data_cursor(self) -> dict[str, int] | None:
        """4.2/4.4: the LIVE data cursor, None when it cannot be read (unknown;
        the cut / same-shape rebuild then refuse instead of comparing a stale
        value). The last generated batch's cursor is ``last_batch_data_cursor``."""
        live, _ = self.live_data_cursor()
        return None if live is None else dict(live)

    def last_batch_data_cursor(self) -> dict[str, int] | None:
        """The cursor the rollout metadata reported after the last batch (cache)."""
        return None if self._last_cursor is None else dict(self._last_cursor)

    def generate(
        self, rollout_id: int, *, expected_policy_version: str | None = None
    ) -> RolloutBatchHandle:
        policy_version, policy_hash = self._expected_policy()
        token = policy_token(policy_version, policy_hash)
        if expected_policy_version is not None and expected_policy_version != token:
            # IR-3: the driver's target token and the published policy this
            # pool serves must be the same object; refuse before any sampling.
            from yeto.rl.engine.driver import PolicyIdentityError  # driver never imports the adapter

            raise PolicyIdentityError(
                f"rollout {rollout_id}: driver expects {expected_policy_version}, "
                f"the pool serves {token}"
            )
        setter = getattr(self._metadata, "set_policy_token", None)
        if setter is not None:  # rollout-side group-reuse filter + agentic generate read it
            setter(token)
        self._run(self._controller.prepare_rollout(rollout_id))
        data_pack = self._run(self._executor.get(rollout_id))
        self._offload_after_rollout()
        try:
            payload = self._metadata.take(rollout_id)
            handle = handle_from_metadata(
                payload,
                rollout_id=rollout_id,
                policy_version=policy_version,
                policy_hash=policy_hash,
                data_pack=data_pack,
            )
        except BaseException:
            _release(data_pack)
            raise
        self._last_cursor = dict(handle.data_cursor) if handle.data_cursor else None
        return handle

    #: min seconds between two "load_sample unavailable" diagnostics
    LOAD_DIAG_INTERVAL_S = 60.0

    def _load_diag(self, reason: str) -> None:
        """Rate-limited, reasoned log when the load probe yields nothing (fnA try27:
        0 ``rl_load_sample`` with no trace of why)."""
        now = time.monotonic()
        last = getattr(self, "_load_diag_last", None)
        if last is not None and last[0] == reason and now - last[1] < self.LOAD_DIAG_INTERVAL_S:
            return
        self._load_diag_last = (reason, now)
        logger.warning("yeto load_sample unavailable: %s", reason)

    def _router_inflight(self, http_get: Callable[[str], Any]) -> dict[str, Any] | None:
        """Per-engine in-flight counts from the router.

        Miles router (``--use-miles-router``, fork M3): ``GET /worker_inflight``.
        The stock sglang-router / sgl-model-gateway (Miles' default when
        ``use_miles_router`` is False, e.g. non-elastic Flash-Next stage A) has no
        such route; fall back to its ``GET /workers`` (``{"workers": [{"url",
        "load", ...}]}``, ``load`` = router-side in-flight). No cordon there: 0.
        """
        args = self._args
        ip = getattr(args, "sglang_router_ip", None)
        port = getattr(args, "sglang_router_port", None)
        if not ip or not port:
            self._load_diag(f"router address unknown (sglang_router_ip={ip!r} "
                            f"sglang_router_port={port!r})")
            return None
        base = f"http://{ip}:{port}"
        errors = []
        try:
            data = http_get(base + "/worker_inflight")
        except Exception as exc:  # noqa: BLE001 - observation only; absent endpoint = unknown
            errors.append(f"GET {base}/worker_inflight failed: {type(exc).__name__}: {exc}")
        else:
            inflight = data.get("inflight") if isinstance(data, dict) else None
            if isinstance(inflight, dict):
                return {"inflight": inflight, "cordoned": data.get("cordoned") or ()}
            errors.append(f"GET {base}/worker_inflight: no 'inflight' dict ({type(data).__name__})")
        try:
            data = http_get(base + "/workers")
        except Exception as exc:  # noqa: BLE001
            errors.append(f"GET {base}/workers failed: {type(exc).__name__}: {exc}")
        else:
            workers = data.get("workers") if isinstance(data, dict) else None
            if isinstance(workers, list):
                inflight = {}
                for w in workers:
                    if isinstance(w, dict) and w.get("url") and isinstance(w.get("load"), int):
                        inflight[str(w["url"])] = int(w["load"])
                if inflight:
                    return {"inflight": inflight, "cordoned": ()}
            errors.append(f"GET {base}/workers: no workers with url/load")
        self._load_diag("; ".join(errors)
                        + f" (use_miles_router={getattr(args, 'use_miles_router', None)!r})")
        return None

    def _tool_wait_count(self) -> int | None:
        source = self._load_tool_wait
        if source is None:
            return None
        if source == TOOL_WAIT_NO_BOARD_STOCK:
            return 0
        from yeto.rl.engine.tool_wait import read_tool_wait

        try:
            return int(read_tool_wait(source).in_flight)
        except Exception:  # noqa: BLE001 - observation only: unknown
            return None

    def load_sample(self, *, http_get: Callable[[str], Any] | None = None) -> dict[str, Any] | None:
        """rl-infra-spec 1.7: one load sample for ``timeline.classify_load``.

        * ``active_requests``/``workers``/``cordoned``: fork-M3 router
          ``GET /worker_inflight`` (E1's drain reads ``active_requests``);
        * ``running_requests``/``queued_requests``: sum over engines of SGLang
          ``GET /get_load`` (``num_reqs - num_waiting_reqs`` / ``num_waiting_reqs``);
        * ``engine_capacity``: sum over engines of SGLang ``/server_info``
          ``effective_max_running_requests_per_dp`` (read once per engine);
        * ``tool_wait_trajectories``: the ToolWaitBoard count (0 for stock
          generate, None = unknown);
        * ``load_class``: ``classify_load`` of the above, ``"unknown"`` if any
          input is unknown. ``ready_groups`` is not observable mid-rollout: None.

        None when the router (and its ``/workers`` fallback) is unknown: unknown,
        never reported as 0; a rate-limited warning names the reason. A failing engine endpoint makes its field None.
        """
        get = http_get or _http_get_json
        router = self._router_inflight(get)
        if router is None:
            return None
        inflight = router["inflight"]
        sample: dict[str, Any] = {
            "active_requests": int(sum(int(v) for v in inflight.values())),
            "workers": len(inflight),
            "cordoned": len(router["cordoned"]),
        }
        running: int | None = 0
        queued: int | None = 0
        capacity: int | None = 0
        kv_used: int | None = 0
        kv_capacity: int | None = 0
        for url in sorted(inflight):
            base = url.rstrip("/")
            try:
                entries = get(base + "/get_load")
                load = _engine_load(entries)
            except Exception:  # noqa: BLE001
                entries = load = None
            used = _engine_kv_used(entries)
            kv_used = None if used is None or kv_used is None else kv_used + used
            if load is None:
                running = queued = None
            elif running is not None:
                running += load[0]
                queued += load[1]
            if url not in self._capacity:
                try:
                    info = get(base + "/server_info")
                except Exception:  # noqa: BLE001
                    info = None
                cap = _engine_capacity(info)
                if cap is not None:
                    self._capacity[url] = cap
                kv_cap = _engine_kv_capacity(info)
                if kv_cap is not None:
                    self._kv_capacity[url] = kv_cap
            cap = self._capacity.get(url)
            capacity = None if cap is None or capacity is None else capacity + cap
            kv_cap = self._kv_capacity.get(url)
            kv_capacity = None if kv_cap is None or kv_capacity is None else kv_capacity + kv_cap
        tool = self._tool_wait_count()
        sample.update(
            running_requests=running,
            queued_requests=queued,
            engine_capacity=capacity or None,
            tool_wait_trajectories=tool,
            ready_groups=None,
        )
        # agentic-rollout-utilization 1.3 (only when the engines report them, so
        # older engines' load samples are unchanged)
        if kv_used is not None and inflight:
            sample["kv_used_tokens"] = kv_used
        if kv_capacity and inflight:
            sample["kv_capacity_tokens"] = kv_capacity
        harness = self._harness_snapshot()  # IR-2/IR-4; None = unknown
        sample.update(
            harness_in_flight=None if harness is None else int(harness.in_flight),
            env_live=None if harness is None else int(harness.env_live),
            tito_session_mismatch=None if harness is None else int(harness.tito_session_mismatch),
            tito_chain_breaks=None if harness is None else dict(harness.tito_chain_breaks),
            policy_age_violation=None if harness is None else int(harness.policy_age_violation),
        )
        from yeto.rl.engine.timeline import LoadSample, classify_load

        known = None not in (running, queued, sample["engine_capacity"], tool)
        sample["load_class"] = (
            classify_load(LoadSample(queued_requests=queued, active_requests=running,
                                     tool_wait_trajectories=tool, ready_groups=0,
                                     engine_capacity=sample["engine_capacity"],
                                     harness_in_flight=sample["harness_in_flight"] or 0,
                                     env_live=sample["env_live"] or 0))
            if known else "unknown"
        )
        return sample

    def _harness_snapshot(self):
        """IR-2: the harness snapshot (explicit zeros without a harness; None = unknown)."""
        source = self._harness
        if source is None:
            return None
        from yeto.rl.engine.tool_wait import HARNESS_ZERO, read_harness

        if source == HARNESS_NOT_AGENTIC:
            return HARNESS_ZERO
        try:
            return read_harness(source)
        except Exception:  # noqa: BLE001 - unknown: fail closed
            return None

    def _harness_admission(self, method: str, members: frozenset[str]) -> None:
        """IR-2: close/open harness admission to ``members`` (no-op without a board)."""
        source = self._harness
        if source is None or source == HARNESS_NOT_AGENTIC:
            return
        from yeto.rl.engine.tool_wait import _call, _resolve

        _resolve(_call(source, method, sorted(members)))

    def _offload_after_rollout(self) -> None:
        """Upstream ``train.py`` serial colocated branch (--offload-rollout)."""

        args = self._args
        if args is None or not getattr(args, "offload_rollout", False):
            return
        if getattr(args, "colocate_memory_peak_device", None) == "gpu":
            self._run(self._controller.offload_kv())
            return
        from sglang.srt.constants import (
            GPU_MEMORY_TYPE_CUDA_GRAPH,
            GPU_MEMORY_TYPE_KV_CACHE,
            GPU_MEMORY_TYPE_WEIGHTS,
        )

        level = str(getattr(args, "offload_rollout_level", "") or "")
        tags = [GPU_MEMORY_TYPE_CUDA_GRAPH]
        if "kv_cache" in level:
            tags.append(GPU_MEMORY_TYPE_KV_CACHE)
        if "weight" in level:
            tags.append(GPU_MEMORY_TYPE_WEIGHTS)
        self._run(self._controller.offload(tags=tags))

    def abort(self) -> None:
        self._run(self._controller.abort_all())

    def members(self) -> frozenset[str]:
        return self._run(running_members(self._controller))

    # -- E1 membership verbs (3.4) ---------------------------------------------
    def _require_declared(self) -> tuple[str, ...]:
        if not self._declared:
            raise MembershipPlanError("no declared rollout cells: E1 membership verbs are off")
        return self._declared

    def plan_add(self, count: int) -> frozenset[str]:
        declared = self._require_declared()
        if count < 1:
            raise MembershipPlanError(f"add_engines needs a positive count, got {count}")
        tracked = set(self._run(self._controller.get_cell_statuses()) or {})
        free = [c for c in declared if c not in tracked]
        if len(free) < count:
            raise MembershipPlanError(
                f"{count} engines requested, only {len(free)} declared cells are stopped: {free}"
            )
        return frozenset(member_id(c) for c in free[:count])

    def add_engines(
        self, count: int, *, epoch: int, members: frozenset[str] | None = None
    ) -> frozenset[str]:
        """Start ``count`` declared cells and wait until the servers track them.

        The cells take no traffic until a member publication admits them (3.5).
        Returns the started members. A timeout while waiting for tracking leaves
        the fork epoch committed (the caller's journal sees ``epoch + 1``).
        """
        chosen = frozenset(members) if members is not None else self.plan_add(count)
        if len(chosen) != count:
            raise MembershipPlanError(f"{len(chosen)} members named for {count} engines")
        cells = cells_of(chosen)
        unknown = sorted(set(cells) - set(self._require_declared()))
        if unknown:
            raise MembershipPlanError(f"cells {unknown} were not declared at startup")
        if self._inject_start_delay is not None and not self.injected_start_delays:
            import sys

            print(f"[yeto] TEST INJECTION {INJECT_START_DELAY_ENV}: sleeping "
                  f"{self._inject_start_delay}s before start_cells({cells})", file=sys.stderr, flush=True)
            self.injected_start_delays.append(self._inject_start_delay)
            self._sleep(self._inject_start_delay)
        self._run(self._controller.start_cells(cells, expected_epoch=epoch))
        self._run(self._controller.wait_cells_tracked(cells, timeout_seconds=self._track_timeout_s))
        return chosen

    def _manager(self) -> Any:
        if self._worker_manager is None:
            from miles.utils.workers.ray_worker_manager import RayWorkerManager

            self._worker_manager = RayWorkerManager.get_handle()
        return self._worker_manager

    def member_gpus(self, members: Any = None) -> dict[str, tuple[str, ...]]:
        """Pool GPU ids each member (declared cell) is bound to now (E3 H2: choose
        the members to remove by the GPUs a transfer moves). Read from the fork's
        ``RayWorkerManager.get_cell_bundles`` and mapped back through the startup
        bundle map; ``members`` None = the serving members."""
        declared = self._require_declared()
        if self._bundles is None:
            raise MembershipPlanError("no GPU -> bundle view mapping: cannot report member GPUs")
        cells = cells_of(self.members() if members is None else frozenset(members))
        unknown = sorted(set(cells) - set(declared))
        if unknown:
            raise MembershipPlanError(f"cells {unknown} were not declared at startup")
        describe = getattr(self._controller, "describe_cells", None)
        if callable(describe):
            # fork F-R1: the controller reports each declared cell's bundles
            # (reordered bundle indices of the startup placement group)
            described = dict(self._run(describe()) or {})
            missing = sorted(set(cells) - set(described))
            if missing:
                raise MembershipPlanError(f"the fork does not describe cells {missing}")
            bundles = {c: list(described[c].get("bundles") or []) for c in cells}
        else:
            manager = self._manager()

            async def read() -> dict[str, list[int]]:
                return {c: list(await manager.get_cell_bundles.remote(c)) for c in cells}

            bundles = self._run(read())
        return {member_id(c): self._bundles.gpus_for_bundles(b) for c, b in sorted(bundles.items())}

    def members_on_gpus(self, gpus: Any, members: Any = None) -> frozenset[str]:
        """Members whose GPUs all lie in ``gpus`` (and none elsewhere)."""
        wanted = {str(g) for g in gpus}
        return frozenset(m for m, owned in self.member_gpus(members).items()
                         if owned and set(owned) <= wanted)

    def bind_members(self, members: frozenset[str], gpus: tuple[str, ...]) -> str:
        """Bind stopped declared cells to the GPUs a trainer released (E3 role transfer, 4.7).

        Points a fresh placement-group view (fork-M6 ``set_pg_view``) at the
        startup bundles of ``gpus`` and rebinds each cell (``rebind_cell``) to
        consecutive slots of it, in sorted member order, so the next
        ``add_engines`` starts them there. Returns the view name.

        Depends on fork gap F-R1: the fork (M1) cannot declare at startup a
        stopped rollout cell whose default binding lies outside the rollout
        view, so on the real fork there may be no such cell to bind yet.
        """
        declared = self._require_declared()
        cells = sorted(cells_of(frozenset(members)))
        unknown = sorted(set(cells) - set(declared))
        if unknown:
            raise MembershipPlanError(f"cells {unknown} were not declared at startup")
        if not cells:
            raise MembershipPlanError("bind_members needs at least one member")
        per = int(self._gpus_per_engine or getattr(self._args, "rollout_num_gpus_per_engine", 1) or 1)
        gpus = tuple(str(g) for g in gpus)
        if len(gpus) != per * len(cells) or len(set(gpus)) != len(gpus):
            raise MembershipPlanError(
                f"{len(cells)} engines x {per} GPUs need {per * len(cells)} distinct GPUs, got {list(gpus)}")
        if self._bundles is None:
            raise MembershipPlanError("no GPU -> bundle view mapping: cannot bind engines to GPUs")
        tracked = set(self._run(self._controller.get_cell_statuses()) or {})
        running = sorted(set(cells) & tracked)
        if running:
            raise MembershipPlanError(f"cells {running} are running; only stopped cells can be bound")
        cross = bool(getattr(self._args, "yeto_rl_allow_cross_node_engine_tp", False))
        for i, cell in enumerate(cells):  # rl-multinode-island D7: a cell never spans nodes by default
            run = gpus[i * per:(i + 1) * per]
            if not self._bundles.same_node(run):
                # ruling 2026-10-04 v2: with the explicit opt-in a cross-node engine is one
                # replica of WHOLE nodes (every node contributes all its GPUs)
                if not cross:
                    raise MembershipPlanError(f"cell {cell} target GPUs {list(run)} span nodes "
                                              "(--rl-allow-cross-node-engine-tp lifts the default)")
                g = int(self._bundles.gpus_per_node or 0)
                counts: dict = {}
                for gpu in run:
                    node = self._bundles.node_of(str(gpu))
                    counts[node] = counts.get(node, 0) + 1
                if g and any(c != g for c in counts.values()):
                    raise MembershipPlanError(f"cell {cell} target GPUs {list(run)} do not take whole "
                                              f"{g}-GPU nodes (one cross-node replica = all its nodes)")
        info = self._bundles.view_for(gpus)
        manager = self._manager()
        self._bind_seq += 1
        view = f"yeto-rollout-bind-{self._bind_seq}-{'-'.join(cells)}"

        async def bind() -> None:
            await manager.set_pg_view.remote(view, info)
            for i, cell in enumerate(cells):
                await manager.rebind_cell.remote(cell, pg_name=view, pg_slot_offset=i * per)

        self._run(bind())
        return view

    def unbind_members(self, members: frozenset[str]) -> None:
        """Return stopped deferred cells to unbound (fork F-R1 ``unbind_cell``), so
        their bundles are free for a growing trainer (4.7 rollout->trainer, after
        ``remove_engines``). Only cells declared stopped (``start: false``) can be
        unbound; a startup-started cell keeps its bundles (the fork asserts)."""
        cells = sorted(cells_of(frozenset(members)))
        unknown = sorted(set(cells) - set(self._require_declared()))
        if unknown:
            raise MembershipPlanError(f"cells {unknown} were not declared at startup")
        manager = self._manager()

        async def unbind() -> None:
            for cell in cells:
                await manager.unbind_cell.remote(cell)

        self._run(unbind())

    def remove_engines(self, members: frozenset[str], *, epoch: int) -> frozenset[str]:
        """Deregister and stop ``members`` (drain them first); returns the remaining members."""
        if self._stop_failures_left > 0:
            self._arm_stop_failure()
        self._run(self._controller.stop_cells(cells_of(members), expected_epoch=epoch))
        return self.members()

    def _arm_stop_failure(self) -> None:
        """TEST ONLY: make the fork's engine provider fail this stop once (the fork
        then marks the membership ``incomplete``, its real half-failure path).

        The real controller is a Ray actor (behind Miles' ``RayWorkerHandle``): the
        provider only exists inside it, so the arming runs there via ``__ray_call__``
        (GPU d123, chain 2: reading ``_engine_provider`` through the handle returned a
        remote-call function and the stop failed with AttributeError instead of the
        fork's incomplete path). In-process controllers (tests) are patched directly."""
        kind, target = _executor_target(self._controller)
        import sys

        if kind == "ray":
            remote = getattr(getattr(target, "__ray_call__", None), "remote", None)
            if not callable(remote):
                raise MembershipPlanError("stop failure injection: the fork controller handle has no __ray_call__")
            receipt = self._run(_awaited(remote(arm_stop_failure_in_controller)))
            self._stop_failures_left -= 1
            self.injected_stop_failures += 1
            print(f"[yeto] TEST INJECTION {INJECT_STOP_FAILURES_ENV}: armed inside the fork controller "
                  f"actor (provider {receipt}); its next stop_cells fails once", file=sys.stderr, flush=True)
            if self.event_sink is not None:
                self.event_sink("test_injection", kind="stop_failure", applied=True, where="fork_actor",
                                provider=str(receipt), remaining=self._stop_failures_left)
            return
        provider = getattr(self._controller, "_engine_provider", None)
        if provider is None or not hasattr(provider, "stop_cells"):
            raise MembershipPlanError("stop failure injection: the fork has no engine provider")
        real = provider.stop_cells
        pool = self

        async def failing_stop(*args: Any, **kwargs: Any) -> Any:
            provider.stop_cells = real  # one shot
            pool._stop_failures_left -= 1
            pool.injected_stop_failures += 1
            import sys

            print(f"[yeto] TEST INJECTION {INJECT_STOP_FAILURES_ENV}: provider stop_cells fails",
                  file=sys.stderr, flush=True)
            raise RuntimeError("injected provider stop failure (test)")

        provider.stop_cells = failing_stop

    def drain(self, members: frozenset[str], deadline: float) -> bool:
        """Cordon ``members`` and wait for zero in-flight requests until ``deadline`` (wall clock).

        False at the deadline; nothing is aborted, members stay cordoned
        (:meth:`undrain` cancels). The router counts engine requests only; a
        trajectory waiting on a tool is counted by yeto (3.3), not here.
        """
        # IR-2: harness admission closes BEFORE the router cordon, so no new
        # session can target a draining member while its engines quiesce.
        self._harness_admission("close_admission", members)
        self._maybe_inject_tool_wait(members)
        timeout = max(0.0, float(deadline) - time.time())
        return bool(self._run(self._controller.drain_cells(cells_of(members),
                                                           timeout_seconds=timeout)))

    def _maybe_inject_tool_wait(self, members: frozenset[str]) -> None:
        """TEST ONLY (INJECT_TOOL_WAIT_ENV): count one artificial trajectory as waiting on
        a tool for N seconds, so the drain's tool-wait condition holds that long.

        The injected tool *executes* on every drain call (its external side effect
        = the ``tool_side_effect`` record written before the board entry, when a
        side-effect log is configured). It is not re-armed while its previous
        execution is still waiting: a second drain of the same members during
        that wait is journaled (the replay evidence) but ``applied`` is False.
        """
        if self._inject_tool_wait is None:
            return
        import sys
        import threading

        from yeto.rl.engine.tool_wait import _call, _resolve

        seconds = self._inject_tool_wait
        self.injected_tool_waits.append(seconds)
        call_id = injected_tool_call_id(members)
        attempt = len(self.injected_tool_waits)
        if self._side_effects is not None:
            try:
                self._side_effects.record(INJECTED_TOOL_WAIT_ID, call_id, seconds=seconds,
                                          target_members=sorted(members), attempt=attempt)
            except Exception as exc:  # noqa: BLE001 - evidence must not break the drain
                print(f"[yeto] side-effect log write failed: {exc!r}", file=sys.stderr, flush=True)
        applied, error = False, None
        if self._tool_wait_board is None:
            error = "no ToolWaitBoard"
        else:
            try:
                _resolve(_call(self._tool_wait_board, "enter", INJECTED_TOOL_WAIT_ID))
                applied = True
            except Exception as exc:  # noqa: BLE001 - recorded: applied=false
                error = repr(exc)
        print(f"[yeto] TEST INJECTION {INJECT_TOOL_WAIT_ENV}: tool-wait entry for {seconds}s "
              f"during the drain of {sorted(members)} (applied={applied}, attempt={attempt})",
              file=sys.stderr, flush=True)
        if self.event_sink is not None:
            self.event_sink("test_injection", kind="tool_wait",
                            target_members=sorted(members), seconds=seconds, applied=applied,
                            tool_call_id=call_id, attempt=attempt,
                            side_effect_log=self._side_effects is not None,
                            **({"error": error} if error else {}))
        if applied:
            board = self._tool_wait_board
            side_effects = self._side_effects

            def release() -> None:
                try:
                    _resolve(_call(board, "exit", INJECTED_TOOL_WAIT_ID))
                except Exception:  # noqa: BLE001 - board gone with the run
                    pass
                if side_effects is not None:
                    try:
                        side_effects.complete(INJECTED_TOOL_WAIT_ID, call_id, attempt=attempt)
                    except Exception:  # noqa: BLE001
                        pass

            timer = threading.Timer(seconds, release)
            timer.daemon = True
            timer.start()

    def undrain(self, members: frozenset[str]) -> None:
        if self._inject_undrain_fail > 0:
            import sys

            self._inject_undrain_fail -= 1
            self.injected_undrain_failures.append(frozenset(members))
            print(f"[yeto] TEST INJECTION {INJECT_UNDRAIN_FAIL_ENV}: undrain of {sorted(members)} "
                  "fails (the cordoned members stay cordoned)", file=sys.stderr, flush=True)
            if self.event_sink is not None:
                self.event_sink("test_injection", kind="undrain_fail",
                                target_members=sorted(members), applied=True)
            raise RuntimeError("injected undrain failure: uncordon not performed")
        self._run(self._controller.uncordon_cells(cells_of(members)))
        self._harness_admission("open_admission", members)  # IR-2: after the uncordon

    def trajectory_load(self) -> dict[str, Any] | None:
        """3.3 drain probe: router in-flight + in-flight tool waits (``tool_wait.drain_blockers``).

        None without a tool-wait board (the controller then relies on the
        serial round boundary only). Unknown counts are reported as blockers
        (fail closed).
        """
        if self._tool_wait_board is None:
            return None
        from yeto.rl.engine.tool_wait import drain_blockers, read_tool_wait

        sample = self.load_sample()
        active = None if sample is None else int(sample["active_requests"])
        try:
            snap = read_tool_wait(self._tool_wait_board)
        except Exception:  # noqa: BLE001 - unknown: fail closed below
            snap = None
        harness = self._harness_snapshot()  # IR-2: None = unknown (fail closed)
        return {
            "active_requests": active,
            "tool_wait": None if snap is None else int(snap.in_flight),
            "harness_in_flight": None if harness is None else int(harness.in_flight),
            "env_live": None if harness is None else int(harness.env_live),
            "env_live_deadline": None if harness is None else harness.latest_lease_deadline,
            "blockers": drain_blockers(active, snap, harness),
        }

    def member_states(self) -> dict[str, dict[str, Any]] | None:
        """Per declared member (fork F-R1 ``describe_cells``): ``state`` (unbound /
        stopped / running), ``tracked``, ``serving``, ``awaiting_admission``. Used by
        the restart recovery (3.7) to refuse unbound targets and to verify router
        admission before release. None on a fork without ``describe_cells``."""
        describe = getattr(self._controller, "describe_cells", None)
        if not callable(describe):
            return None
        described = dict(self._run(describe()) or {})
        return {
            member_id(c): {"state": d.get("state"), "tracked": bool(d.get("tracked")),
                           "serving": bool(d.get("serving")),
                           "awaiting_admission": bool(d.get("awaiting_admission"))}
            for c, d in described.items() if isinstance(d, dict)
        }

    def membership_status(self) -> dict[str, Any]:
        status = dict(self._run(self._controller.get_membership_status()))
        incomplete = status.get("incomplete")
        if incomplete:
            status["incomplete"] = [incomplete[0], [member_id(c) for c in incomplete[1]]]
        return status

    def restore_membership(
        self, *, epoch: int, incomplete: Any, last_op: Any, expected_current_epoch: int
    ) -> dict[str, Any]:
        def cells(value: Any) -> Any:
            return None if value is None else [value[0], cells_of(value[1])]

        return dict(self._run(self._controller.restore_membership_state(
            epoch=epoch, incomplete=cells(incomplete), last_op=cells(last_op),
            expected_current_epoch=expected_current_epoch,
        )))


def _release(data_pack: Any) -> None:
    try:
        from miles.utils.data import remove_rollout_data_refs
    except ImportError:  # pragma: no cover - only without miles (tests)
        return
    remove_rollout_data_refs(None, data_pack)
