#!/usr/bin/env python3
"""Generate s19-critic-g3.sh from s19-lpg-neg.sh + the s17-g1-island.sh killer (S19 critic group)."""
B = '/home/michael/work/s1-runs/'
s = open(B + 's19-lpg-neg.sh').read()
k = open(B + 's17-g1-island.sh').read()


def rep(old, new):
    global s
    assert s.count(old) == 1, old[:80]
    s = s.replace(old, new)


L = s.split('\n')
hdr = '''#!/bin/bash
# S19 critic group G3 two-island strict-avg (#2 SAO G3, #5 PPO + kill/resume, #6 VAPO G3).
#   Generated by s19-critic-g3-gen.py from s19-lpg-neg.sh (teardown pulls head logs FIRST; systemd-run watchdog)
#   + the s17-g1-island.sh killer. Nebius eu-north1 CPU head (controller + syncers) + 2x Modal H100!.
#   Launch submit holds GPU-LAUNCH.lock (fd 9 closed in every background child) until both islands report a GPU.
# usage: CASE=ppo|sao|vapo s19-critic-g3.sh <run_id>   env: KILL=1 (ppo), STEPS=3, HARD, PLAN_ONLY=1'''
i0 = [i for i, l in enumerate(L) if l.startswith('set -u')][0]
s = '\n'.join(hdr.split('\n') + L[i0:])
rep('P=${1:?run id}; OV=${OV:?OV}; HARD=${HARD:-3600}; STEPS=${STEPS:-6}; KILL_AT_V=${KILL_AT_V:-2}',
    'P=${1:?run id}; CASE=${CASE:?CASE}; HARD=${HARD:-4800}; STEPS=${STEPS:-3}; KILL_AT_V=${KILL_AT_V:-1}')
rep('KILL_ISLAND=${KILL_ISLAND:-0}', 'KILL_ISLAND=${KILL_ISLAND:-1}')
rep('SCHED=${SCHED:-elastic}', 'SCHED=${SCHED:-legacy}')
rep('REPO=${REPO:-/home/michael/work/s19-b3x}', 'REPO=${REPO:-/home/michael/work/s19-critic}')
old_img = [l for l in s.split('\n') if l.startswith('IMAGE=$(cd')][0]
rep(old_img, 'IMAGE=docker:ghcr.io/michaellchung/yeto-miles-ports@sha256:fa2413be4c4fcf066437f946365f01392d6f884002f8fa19c770c12c08f2acf0  # S19 #1 (PR #188)')
rep('T=$(ps -u michael -L -o pid= | wc -l)  # logged only; the launcher preflight is the gate',
    "T=$(ps -eLo user= | grep -c '^michael')")
rep('grep -q -- "--rl-elastic-debug-pause" $REPO/yeto/cli.py || { echo "abort: $REPO cli lacks --rl-elastic-debug-pause"; exit 64; }\n', '')
rep('[ -n "${SPEC:-}" ] && cp $SPEC $R/yeto/g1-spec.json', 'cp $B/s19-critic-specs/$CASE.json $R/yeto/g1-spec.json')
oldm = [l for l in s.split('\n') if l.startswith('MODEL=')][0]
rep(oldm, '''case $CASE in
  sao) MODEL="--model Qwen/Qwen3.5-0.8B --model-revision 2fc06364715b967f1860aea9cf38778875588b17"; LORA="--tuning lora --lora-r 16 --lora-targets attention"; LRS="--rl-lr-schedule constant";;
  *)   MODEL="--model Qwen/Qwen3-0.6B --model-revision c1899de289a04d12100db370d81485cdf75e47ca"; LORA="--tuning lora --lora-r 16 --lora-targets all-linear"; LRS="";;
esac
ALLOW=""; while read -r a; do [ -n "$a" ] && ALLOW="$ALLOW --rl-allow-unverified-mechanism $a"; done < $B/s19-critic-specs/$CASE.allow''')
rep('MODALX="--modal-gpu-exact --modal-retries 0 --modal-timeout-s $MODAL_TIMEOUT --modal-tape-volume $TAPEVOL"',
    'MODALX="--modal-gpu-exact --modal-retries 0 $( [ "${KILL:-0}" = 1 ] && echo "--modal-launcher-relaunch --recover-timeout 1800 " || echo "--no-island-relaunch ")--modal-timeout-s $MODAL_TIMEOUT --modal-tape-volume $TAPEVOL"')
rep('${SPEC:+--rl-algorithm-spec g1-spec.json }', '--rl-algorithm-spec g1-spec.json $ALLOW $LRS ')
rep('--rl-negative-test-run --rl-island-override $OV --preflight-threads wait', '--preflight-threads wait')
rep('echo "PLAN_ONLY run=$P app=$APP head=$HEAD_CL sched=$SCHED ov=$OV steps=$STEPS',
    'echo "PLAN_ONLY run=$P case=$CASE kill=${KILL:-0} app=$APP head=$HEAD_CL sched=$SCHED steps=$STEPS')
rep("t.startswith(('rl-lr','rl-max-policy','rl-island-sched'))",
    "t.startswith(('rl-lr','rl-max-policy','rl-island-sched','rl-algorithm','rl-stall','modal-launcher','no-island'))")
ks = k.index('# killer (runs ON the head VM')
ke = k.index('cp $B/s15-island1b-rejoin-stopper.py')
rep('echo "ps_threads_at_start=$T" > $R/threads-ps.txt\n', 'echo "ps_threads_at_start=$T" > $R/threads-ps.txt\n' + k[ks:ke])
rep('''cd $R/yeto
( eval "timeout $HARD $PY -m yeto.cli $(cat $R/args.txt)" 2>&1 | tee $R/launch.stream.log | awk '{ print strftime("%FT%TZ", systime(), 1) " " $0; fflush() }' > $R/launch.ts.log; echo "rc=${PIPESTATUS[0]}" > $R/submit_rc.txt ) &''',
    '''cd $R/yeto
exec 9>/home/michael/work/infra-drafts/GPU-LAUNCH.lock; flock 9
T2=$(ps -eLo user= | grep -c '^michael'); echo "threads_at_lock=$T2" >> $R/threads-ps.txt
[ "$T2" -lt 2800 ] || { echo "abort: $T2 threads"; exec 9>&-; systemctl --user stop $P-wd.timer; exit 3; }
( eval "timeout $HARD $PY -m yeto.cli $(cat $R/args.txt)" 2>&1 | tee $R/launch.stream.log | awk '{ print strftime("%FT%TZ", systime(), 1) " " $0; fflush() }' > $R/launch.ts.log; echo "rc=${PIPESTATUS[0]}" > $R/submit_rc.txt ) 9>&- &''')
rep('echo "head_job=$JOB" > $R/head_job.txt\nwait $SUB', '''echo "head_job=$JOB" > $R/head_job.txt
if [ -n "$JOB" ] && [ "${KILL:-0}" = 1 ]; then
  cat > $R/killer.yaml <<EOF
name: critic-g3-killer
run: |
  for i in \\$(seq 1 180); do [ -f ~/.yeto_head_ready ] && break; sleep 5; done
  if [ -x ~/yeto-head-py/bin/python3 ]; then export PATH=~/yeto-head-py/bin:\\$PATH; fi
  python3 -c "import modal; print('killer modal', modal.__version__)" || exit 5
  cd ~/sky_workdir && python3 g3_killer.py $L1 $KILL_DELAY $KILL_AT_V $KILL_ISLAND
EOF
  (cd /tmp && timeout 600 $SKY exec -d $HEAD_CL $R/killer.yaml --secret MODAL_TOKEN_ID --secret MODAL_TOKEN_SECRET 9>&-) > $R/killer-submit.log 2>&1
fi
for i in $(seq 1 90); do [ "$(grep -c 'modal-island [01]\\] requested' $R/launch.stream.log 2>/dev/null)" -ge 2 ] && break; kill -0 $SUB 2>/dev/null || break; sleep 10; done
exec 9>&-   # release launch lock
wait $SUB''')
rep('tar czf - yeto-output yeto-syncer.log sky_logs', 'tar czf - yeto-output yeto-syncer.log yeto-critic-syncer.log g3-kill sky_logs')
rep('  [ -s $R/launch.log ] || cp $R/\\${1:-final}-launch.log $R/launch.log\nfi',
    '  [ -s $R/launch.log ] || cp $R/\\${1:-final}-launch.log $R/launch.log\n  cp $R/head/g3-kill/kill.json $R/kill.json 2>/dev/null\nfi')
rep('/usr/bin/python3 $B/s18-lpg-judge.py $R $SCHED $STEPS > $R/judgment.json 2>&1',
    'NOKILL=$( [ "${KILL:-0}" = 1 ] && echo 0 || echo 1 ) /usr/bin/python3 $B/s19-critic-g3-judge.py $R $EXPECT_GPU $STEPS > $R/judgment.json 2>&1')
open(B + 's19-critic-g3.sh', 'w').write(s)
