#!/bin/bash
# S19 critic group G3 two-island strict-avg (#2 SAO G3, #5 PPO + kill/resume, #6 VAPO G3).
#   Generated by s19-critic-g3-gen.py from s19-lpg-neg.sh (teardown pulls head logs FIRST; systemd-run watchdog)
#   + the s17-g1-island.sh killer. Nebius eu-north1 CPU head (controller + syncers) + 2x Modal H100!.
#   Launch submit holds GPU-LAUNCH.lock (fd 9 closed in every background child) until both islands report a GPU.
# usage: CASE=ppo|sao|vapo s19-critic-g3.sh <run_id>   env: KILL=1 (ppo), STEPS=3, HARD, PLAN_ONLY=1
set -u
SCHED=${SCHED:-legacy}; KILL_ISLAND=${KILL_ISLAND:-1}; DELAY=${DELAY:-}; LEASE=${LEASE:-90}; STOP_S=${STOP_S:-$(( LEASE + 30 ))}; P=${1:?run id}; CASE=${CASE:?CASE}; HARD=${HARD:-4800}; STEPS=${STEPS:-3}; KILL_AT_V=${KILL_AT_V:-1}; WD=$(( HARD + 600 )); MODAL_TIMEOUT=$HARD; KILL_DELAY=${KILL_DELAY:-20}
REPO=${REPO:-/home/michael/work/s19-critic}; B=/home/michael/work/s1-runs; R=$B/$P
SKY=/home/michael/work/gpu-head/venv/bin/sky; PY=/home/michael/work/gpu-head/venv/bin/python
APP=yeto-$P; TAPEVOL=yeto-event-tapes; EXPECT_GPU=H100; HEAD_REGION=nebius/eu-north1
export CARGO_HOME=/home/michael/work/gpu-default-modal/cargo RUSTUP_HOME=/home/michael/work/gpu-default-modal/rustup
export PATH=$CARGO_HOME/bin:$PATH
IMAGE=docker:ghcr.io/michaellchung/yeto-miles-ports@sha256:fa2413be4c4fcf066437f946365f01392d6f884002f8fa19c770c12c08f2acf0  # S19 #1 (PR #188)
[ -n "$IMAGE" ] || { echo "abort: no MILES_NEXT_IMAGE"; exit 65; }
T=$(ps -eLo user= | grep -c '^michael')
pgrep -x raylet >/dev/null && { echo "abort: local Ray running"; exit 3; }
grep -q 'secrets=secrets or None' $REPO/yeto/cli.py || { echo "abort: $REPO lacks head secrets (s13-g3remote)"; exit 64; }
HEAD_CL=$(cd $REPO && PYTHONPATH=$REPO /usr/bin/python3 -c "from yeto.launcher import sky_cluster_name; print(sky_cluster_name('$P-head'))")
L1=$(cd $REPO && PYTHONPATH=$REPO /usr/bin/python3 -c "
from yeto.launcher import learner_cluster_names; from yeto.gpu_spec import parse_gpu_spec
print(learner_cluster_names('$P', parse_gpu_spec('modal:1xh100,modal:1xh100'))[$KILL_ISLAND])")
if [ "${PLAN_ONLY:-0}" = 1 ]; then R=/tmp/$P-plan; rm -rf $R; fi
[ -e $R/start_utc.txt ] && { echo "abort: $R already used"; exit 67; }
mkdir -p $R/home $R/runs $R/yeto $R/head
# client HOME: everything sky/yeto need EXCEPT ~/.modal.toml (Modal goes by env -> sky secret)
for d in .sky .ssh .nebius .cache .huggingface .config; do [ -e /home/michael/$d ] && ln -sfn /home/michael/$d $R/home/$d; done
git -C $REPO archive ${SHA:-HEAD} | tar x -C $R/yeto
cp /home/michael/work/gpu-default-modal/yeto/gsm8k_reward.py $R/yeto/; touch $R/yeto/yeto-rl-echo-events; cp $B/s19-critic-specs/$CASE.json $R/yeto/g1-spec.json
case $CASE in
  sao*) MODEL="--model Qwen/Qwen3.5-0.8B --model-revision 2fc06364715b967f1860aea9cf38778875588b17"; LORA="--tuning lora --lora-r 16 --lora-targets attention"; LRS="--rl-lr-schedule constant";;
  *)   MODEL="--model Qwen/Qwen3-0.6B --model-revision c1899de289a04d12100db370d81485cdf75e47ca"; LORA="--tuning lora --lora-r 16 --lora-targets all-linear"; LRS="";;
esac
[ "$CASE" = vapo ] && LRS="--rl-lr-schedule constant"  # critic2: critic family uses a constant LR on GPU (PR #190)
ALLOW=""; while read -r a; do [ -n "$a" ] && ALLOW="$ALLOW --rl-allow-unverified-mechanism $a"; done < $B/s19-critic-specs/$CASE.allow
MODALX="--modal-gpu-exact --modal-retries 0 $( [ "${KILL:-0}" = 1 ] && echo "--modal-launcher-relaunch --recover-timeout 1800 " || echo "--no-island-relaunch ")--modal-timeout-s $MODAL_TIMEOUT --modal-tape-volume $TAPEVOL"
ARGS="launch --controller head --syncer-region $HEAD_REGION --training-mode rl --rl-engine ports --rl-island-scheduling $SCHED $( [ "$SCHED" = elastic ] && echo "--rl-soft-deadline-s ${SOFT:-180} ")${DELAY:+--rl-elastic-debug-delay-s $DELAY }$( [ "${PAUSE:-0}" = 1 ] && echo "--rl-elastic-debug-pause ${PAUSE_ISLAND:-1}:${PAUSE_AT_V:-1}:$STOP_S ")--rl-algorithm-spec g1-spec.json $ALLOW $LRS $( [ "$SCHED" = elastic ] && echo "--rl-island-lease-s $LEASE ")--preflight-threads wait --rl-stall-timeout 2400 --rl-observe-timeline --on-demand --gpu modal:1xh100,modal:1xh100 --cluster-prefix $P $MODALX --rl-image $IMAGE $MODEL --data zhuzilin/gsm8k --data-revision 0cbd9f31d91ac21a7613dcbc7fef992adac459ae --reward-function gsm8k_reward:score $LORA --fragments 1 --pipeline 1 --rollout-batch-size 4 --n-samples-per-prompt 8 --rollout-max-response-len 384 --seq-len 1024 --inner-lr 1e-5 --seed 17 --apply-chat-template-kwargs '{\"enable_thinking\": false}' --trust-remote-code --total-steps $STEPS"
git -C $REPO rev-parse ${SHA:-HEAD} > $R/yeto_sha.txt; echo "$ARGS" > $R/args.txt; echo "$APP $HEAD_CL" > $R/resources.txt
# secrets: process env only (never echoed, never written)
eval "$(/usr/bin/python3 - <<'PYC'
import json, shlex, tomllib
t = tomllib.load(open("/home/michael/.modal.toml", "rb"))
prof = next((v for v in t.values() if isinstance(v, dict) and v.get("active")), None) or next(v for v in t.values() if isinstance(v, dict))
print(f"export MODAL_TOKEN_ID={shlex.quote(prof['token_id'])} MODAL_TOKEN_SECRET={shlex.quote(prof['token_secret'])}")
PYC
)"
# island HMAC key (0.20): process env only -> shipped as sky/Modal secret; never written or echoed
export YETO_ISLAND_HMAC_KEY=${YETO_ISLAND_HMAC_KEY:-$(openssl rand -hex 32)}
[ -n "${MODAL_TOKEN_ID:-}" ] || { echo "abort: no modal token"; exit 65; }
export HOME=$R/home YETO_RUNS_DIR=$R/runs PYTHONPATH=$R/yeto
if [ "${PLAN_ONLY:-0}" = 1 ]; then
  echo "PLAN_ONLY run=$P case=$CASE kill=${KILL:-0} app=$APP head=$HEAD_CL sched=$SCHED steps=$STEPS hard=${HARD}s wd=${WD}s code=$REPO@$(cat $R/yeto_sha.txt|cut -c1-8) ps_threads=$T"
  (cd $R/yeto && eval "$PY -m yeto.cli $(cat $R/args.txt) --dry-run") > $R/plan.json 2> $R/plan.err; echo "dry-run rc=$?"; tail -3 $R/plan.err
  /usr/bin/python3 -c "import json,sys;p=json.load(open(sys.argv[1]));[print(i['learner_id'],i.get('island_overrides'),i['memory_estimate'].get('peak_gib'),i['memory_estimate'].get('fits'),[t for t in i['learner_command'].split(' --') if t.startswith(('rl-lr','rl-max-policy','rl-island-sched','rl-algorithm','rl-stall','modal-launcher','no-island'))]) for i in p['island_requests']]" $R/plan.json
  exit 0
fi
date -u +%FT%TZ > $R/start_utc.txt
# teardown of THIS run only (Modal app + head cluster; never `sky down -a`)
cat > $R/teardown.sh <<EOF
cd /tmp; export HOME=/home/michael
S='ssh -o StrictHostKeyChecking=no -o ConnectTimeout=20'
JOB=\$(grep -oP 'head_job=\K\d+' $R/head_job.txt 2>/dev/null)
# 1) pull head evidence BEFORE anything is stopped (launch.log, syncer log, output, queue)
if timeout 60 $SKY status $HEAD_CL 2>/dev/null | grep -q ' UP '; then
  timeout 600 $SKY logs $HEAD_CL \$JOB --no-follow > $R/\${1:-final}-launch.log 2>&1
  timeout 300 $SKY queue $HEAD_CL > $R/head/queue.txt 2>&1
  timeout 600 \$S $HEAD_CL 'cd ~ && tar czf - yeto-output yeto-syncer.log yeto-critic-syncer.log g3-kill sky_logs 2>/dev/null' > $R/head/head-\${1:-final}.tgz 2>/dev/null
  (cd $R/head && tar xzf head-\${1:-final}.tgz 2>/dev/null)
  timeout 60 \$S $HEAD_CL 'hostname; nproc; free -g; ss -ltnp 2>/dev/null|grep -E ":29400"' > $R/head/host.txt 2>&1
  [ -s $R/launch.log ] || cp $R/\${1:-final}-launch.log $R/launch.log
  cp $R/head/g3-kill/kill.json $R/kill.json 2>/dev/null
fi
echo "pulled \$(date -u +%FT%TZ) syncer_log_bytes=\$(stat -c %s $R/head/yeto-syncer.log 2>/dev/null || echo 0)" > $R/\${1:-final}-pull.out
# 2) stop Modal app, 3) down THIS head only (never -a)
timeout 300 $PY -m modal app stop --yes $APP > $R/\${1:-final}-stop.out 2>&1
timeout 900 $SKY down -y $HEAD_CL > $R/\${1:-final}-down.out 2>&1; echo "down rc=\$?" >> $R/\${1:-final}-down.out
sleep 15; timeout 120 $PY -m modal app list --json > $R/\${1:-final}-applist.json 2>&1
timeout 120 $SKY status $HEAD_CL > $R/\${1:-final}-skystatus.txt 2>&1
EOF
systemd-run --user --unit=$P-wd --on-active=${WD}s /bin/bash -c "bash $R/teardown.sh watchdog; touch $R/WATCHDOG_FIRED" > $R/watchdog.out 2>&1
echo "$P-wd.timer" > $R/watchdog.pid
echo "ps_threads_at_start=$T" > $R/threads-ps.txt
# killer (runs ON the head VM as its own sky job; Modal token as sky secret)
cat > $R/yeto/g3_killer.py <<'PY'
import glob, json, os, re, sys, time
import modal  # fail at start, not at kill time (1a-b)
name, delay, at_v, kill_island = sys.argv[1], float(sys.argv[2]), int(sys.argv[3]), int(sys.argv[4]); out = os.path.expanduser("~/g3-kill"); os.makedirs(out, exist_ok=True)
def head_log():
    best = ""
    for p in glob.glob(os.path.expanduser("~/sky_logs/*/run.log")):
        t = open(p, errors="replace").read()
        if "[modal]" in t and "YETO_RL_EVENT" in t and len(t) > len(best): best = t  # 1a-a: head log has no "[yeto]" tag
    return best
deadline = time.time() + 6000
while time.time() < deadline:
    text = head_log()
    calls = re.findall(rf"\[modal\] {re.escape(name)}: function call (\S+)", text)
    applied = False; rounds1 = set()
    for line in text.splitlines():
        at = line.find("YETO_RL_EVENT ")
        if at < 0: continue
        try: e = json.loads(line[at + 14:])
        except ValueError: continue
        if e.get("event") == "rl_policy_apply" and e.get("island_id") == kill_island and e.get("policy_version") == at_v: applied = True
        # 1b fallback: elastic islands may version differently -> also fire after island 1 finished at_v+1 local rounds
        if e.get("event") == "rl_local_round" and e.get("island_id") == kill_island: rounds1.add(e.get("local_round_id"))  # critic runs emit one per channel
    if len(rounds1) >= at_v + 1: applied = True
    if "finished:" in text or "rl_learner_finalized" in text:
        print("run finished before the kill point; no kill", flush=True); sys.exit(2)
    if calls and applied: break
    time.sleep(5)
else:
    print("killer deadline", flush=True); sys.exit(3)
seen = time.time(); time.sleep(delay)
cid = calls[0]
modal.FunctionCall.from_id(cid).cancel(terminate_containers=True)
rec = {"island": name, "call_id": cid, "vN_seen_unix": seen, "kill_unix": time.time()}
open(f"{out}/kill.json", "w").write(json.dumps(rec) + "\n"); print(rec, flush=True)
PY
cd $R/yeto
exec 9>/home/michael/work/infra-drafts/GPU-LAUNCH.lock; flock 9
T2=$(ps -eLo user= | grep -c '^michael'); echo "threads_at_lock=$T2" >> $R/threads-ps.txt
[ "$T2" -lt 2800 ] || { echo "abort: $T2 threads"; exec 9>&-; systemctl --user stop $P-wd.timer; exit 3; }
( eval "timeout $HARD $PY -m yeto.cli $(cat $R/args.txt)" 2>&1 | tee $R/launch.stream.log | awk '{ print strftime("%FT%TZ", systime(), 1) " " $0; fflush() }' > $R/launch.ts.log; echo "rc=${PIPESTATUS[0]}" > $R/submit_rc.txt ) 9>&- &
SUB=$!
# once the controller job is submitted: start the killer job on the VM
JOB=""
for i in $(seq 1 360); do
  JOB=$(grep -oP "submitted: job \K\d+" $R/launch.stream.log 2>/dev/null | head -1); [ -n "$JOB" ] && break
  kill -0 $SUB 2>/dev/null || break; sleep 10
done
echo "head_job=$JOB" > $R/head_job.txt
if [ -n "$JOB" ] && [ "${KILL:-0}" = 1 ]; then
  cat > $R/killer.yaml <<EOF
name: critic-g3-killer
run: |
  for i in \$(seq 1 180); do [ -f ~/.yeto_head_ready ] && break; sleep 5; done
  if [ -x ~/yeto-head-py/bin/python3 ]; then export PATH=~/yeto-head-py/bin:\$PATH; fi
  python3 -c "import modal; print('killer modal', modal.__version__)" || exit 5
  cd ~/sky_workdir && python3 g3_killer.py $L1 $KILL_DELAY $KILL_AT_V $KILL_ISLAND
EOF
  (cd /tmp && timeout 600 $SKY exec -d $HEAD_CL $R/killer.yaml --secret MODAL_TOKEN_ID --secret MODAL_TOKEN_SECRET 9>&-) > $R/killer-submit.log 2>&1
fi
for i in $(seq 1 90); do [ "$(grep -c 'modal-island [01]\] requested' $R/launch.stream.log 2>/dev/null)" -ge 2 ] && break; kill -0 $SUB 2>/dev/null || break; sleep 10; done
exec 9>&-   # release launch lock
wait $SUB
# the stream may drop early: wait (bounded) for the head job to reach a terminal state
if [ -n "$JOB" ]; then
  END=$(( $(date +%s) + HARD ))
  while [ $(date +%s) -lt $END ]; do
    st=$(cd /tmp && timeout 120 $SKY queue $HEAD_CL 2>/dev/null | awk -v j=$JOB '$1==j{print}')
    echo "$st" | grep -qE "RUNNING|PENDING|SETTING_UP|INIT" || break; sleep 30
  done
fi
date -u +%FT%TZ > $R/end_utc.txt
export HOME=/home/michael
bash $R/teardown.sh final
[ -s $R/launch.log ] || cp $R/launch.stream.log $R/launch.log
# rc: the head job's terminal status (SUCCEEDED -> 0)
grep -E "^ *$JOB " $R/head/queue.txt 2>/dev/null | grep -q SUCCEEDED && echo "rc=0" > $R/rc.txt || echo "rc=1 ($(grep -E "^ *$JOB " $R/head/queue.txt 2>/dev/null | tr -s ' ' | cut -c1-120))" > $R/rc.txt
AID=$(/usr/bin/python3 -c "import json,sys;print(next((a['app_id'] for a in json.load(open(sys.argv[1])) if a.get('description')==sys.argv[2]),''))" $R/final-applist.json $APP 2>/dev/null); [ -n "$AID" ] && (cd /tmp && timeout 180 $PY -m modal app logs $AID > $R/modal-app-logs.txt 2>&1)
mkdir -p $R/tape-direct; timeout 600 $PY -m modal volume get --force $TAPEVOL $APP $R/tape-direct > $R/tape-direct.out 2>&1
systemctl --user stop $P-wd.timer 2>/dev/null
NOKILL=$( [ "${KILL:-0}" = 1 ] && echo 0 || echo 1 ) /usr/bin/python3 $B/s19-critic-g3-judge.py $R $EXPECT_GPU $STEPS > $R/judgment.json 2>&1
echo "done $P $(cat $R/rc.txt) judgment=$(head -c 300 $R/judgment.json)"
