#!/usr/bin/env bash
# Draft build script for the verl Ascend (910B4) image -- rl-verl-backend 3.11.
#
# STATUS: draft, never run. No image has been built or pushed with it. Two
# inputs are still unknown (ask the user before running):
#   1. CPU architecture of the 910B4 node: x86_64 or aarch64. The wheels and
#      the CANN library path differ, and an x86 build cannot run on aarch64.
#   2. Whether this network can reach swr.cn-south-1.myhuaweicloud.com, where
#      the CANN base image lives.
#
# The recipe is copied from the pinned verl fork
# (acad9875, docker/ascend/Dockerfile.ascend_9.1.0_a2) and keeps our own pins
# from yeto/rl/adapters/verl/pins.py. The CUDA image is built elsewhere
# (Modal); these are two separate images and two separate version stacks --
# vLLM 0.23 + torch 2.10 + CANN 9.1.0 here, vLLM 0.29 + torch 2.13 there.
#
# Usage:
#   scripts/build_verl_npu_image.sh --arch aarch64 [--soc ascend910b1] \
#       [--tag verl-npu:acad9875] [--print-dockerfile] [--no-build]
set -euo pipefail

ARCH=""
SOC="ascend910b1"          # Dockerfile ARG of the 910B (A2) line
TAG="verl-npu:acad9875"
DO_BUILD=1
PRINT_ONLY=0
OUT_DIR="${TMPDIR:-/tmp}/verl-npu-build"

while [ $# -gt 0 ]; do
  case "$1" in
    --arch) ARCH="$2"; shift 2 ;;
    --soc) SOC="$2"; shift 2 ;;
    --tag) TAG="$2"; shift 2 ;;
    --out-dir) OUT_DIR="$2"; shift 2 ;;
    --no-build) DO_BUILD=0; shift ;;
    --print-dockerfile) PRINT_ONLY=1; DO_BUILD=0; shift ;;
    -h|--help) sed -n '1,25p' "$0"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

if [ -z "$ARCH" ]; then
  echo "error: --arch is required (x86_64 or aarch64)." >&2
  echo "       Run 'uname -m' on the 910B4 node first; the two builds are not" >&2
  echo "       interchangeable." >&2
  exit 2
fi
case "$ARCH" in
  x86_64|aarch64) ;;
  *) echo "error: --arch must be x86_64 or aarch64, got '$ARCH'" >&2; exit 2 ;;
esac

# --- pins (keep in sync with yeto/rl/adapters/verl/pins.py) ------------------
BASE_IMAGE="swr.cn-south-1.myhuaweicloud.com/ascendhub/cann:9.1.0-910b-ubuntu22.04-py3.12"
CANN_VERSION="9.1.0"
VLLM_TAG="v0.23.0"
VLLM_ASCEND_BRANCH="releases/v0.23.0"
MINDSPEED_BRANCH="core_r0.18.0"
MEGATRON_TAG="core_v0.18.0"
TRANSFORMERS_VERSION="5.10.4"
VERL_REPOSITORY="https://github.com/michaellchung/verl"
VERL_COMMIT="acad9875a8bdfc81afbcb0a50d146b2630f44093"

mkdir -p "$OUT_DIR"
DOCKERFILE="$OUT_DIR/Dockerfile.verl-npu-$ARCH"

cat > "$DOCKERFILE" <<EOF
# Generated by scripts/build_verl_npu_image.sh -- do not edit by hand.
# Source recipe: verl fork $VERL_COMMIT docker/ascend/Dockerfile.ascend_9.1.0_a2
FROM $BASE_IMAGE

ARG SOC_VERSION="$SOC"
ENV DEBIAN_FRONTEND=noninteractive
# The CANN env scripts are sourced below, so RUN needs bash, not sh.
SHELL ["/bin/bash", "-c"]
# Ascend device library path; it differs per architecture.
ENV LD_LIBRARY_PATH=/usr/local/Ascend/cann-$CANN_VERSION/$ARCH-linux/devlib/linux/$ARCH:\$LD_LIBRARY_PATH

RUN apt-get update -y && \\
    apt-get install -y --no-install-recommends gcc g++ cmake libnuma-dev wget git curl jq vim build-essential && \\
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \\
    pip install --upgrade pip packaging setuptools==80.10.2 && pip cache purge

EOF

if [ "$ARCH" = "x86_64" ]; then
  cat >> "$DOCKERFILE" <<EOF
# x86_64 only: CPU torch wheels come from the PyTorch index (the NPU build of
# torch gets its device support from torch_npu, not from a CUDA wheel).
RUN pip config set global.extra-index-url "https://download.pytorch.org/whl/cpu/"
EOF
fi

cat >> "$DOCKERFILE" <<EOF

# Repositories with a low update frequency, cloned in one layer.
RUN git clone --depth 1 --branch $VLLM_TAG https://github.com/vllm-project/vllm.git && \\
    git clone -b $VLLM_ASCEND_BRANCH https://github.com/vllm-project/vllm-ascend.git && \\
    git clone --branch $MINDSPEED_BRANCH https://gitcode.com/Ascend/MindSpeed.git && \\
    git clone --depth 1 --branch $MEGATRON_TAG https://github.com/NVIDIA/Megatron-LM.git && \\
    git clone --depth 1 --branch $MINDSPEED_BRANCH https://gitcode.com/ascend/MegatronAdaptor.git && \\
    git clone --depth 1 https://gitcode.com/ascend/TransformerEngineNPU.git && \\
    git clone --depth 1 https://gitcode.com/ascend/MindSpeed-Ops.git && \\
    git clone --depth 1 https://gitcode.com/ascend/MindSpeed-Bridge.git && \\
    git clone --depth 1 --branch v0.5.0 https://github.com/NVIDIA-NeMo/Megatron-Bridge.git

RUN export PIP_EXTRA_INDEX_URL=https://triton-ascend.osinfra.cn/pypi/simple/ && \\
    export PIP_TRUSTED_HOST=triton-ascend.osinfra.cn && \\
    source /usr/local/Ascend/ascend-toolkit/set_env.sh && \\
    source /usr/local/Ascend/nnal/atb/set_env.sh && \\
    cd vllm && VLLM_TARGET_DEVICE=empty pip install -v -e . && cd .. && \\
EOF

if [ "$ARCH" = "x86_64" ]; then
  cat >> "$DOCKERFILE" <<'EOF'
    pip install torch==2.10.0+cpu torchvision==0.25.0+cpu --index-url https://download.pytorch.org/whl/cpu/ && \
EOF
fi

cat >> "$DOCKERFILE" <<EOF
    cd vllm-ascend && pip install -r requirements.txt && \\
    export COMPILE_CUSTOM_KERNELS=1 && pip install --no-build-isolation --no-deps -v -e . && cd .. && \\
    pip install -e Megatron-LM && pip install -e MindSpeed && pip install -e MegatronAdaptor && \\
    pip install -e TransformerEngineNPU --no-build-isolation && \\
    pip install -e MindSpeed-Ops --no-build-isolation --no-deps && \\
    pip install -r MindSpeed-Bridge/requirements.txt && pip install -e MindSpeed-Bridge --no-deps && \\
    pip install -e Megatron-Bridge --no-build-isolation --no-deps && \\
    pip install transformers==$TRANSFORMERS_VERSION && \\
    rm -rf /tmp/* /var/tmp/* && pip cache purge

# Our pinned verl fork, not upstream (the fork is what S16 measured).
RUN git clone $VERL_REPOSITORY verl && cd verl && \\
    git checkout $VERL_COMMIT && git submodule update --init --recursive && \\
    pip install -r requirements-npu.txt && pip install -v -e . --no-deps && \\
    git rev-parse HEAD > /workspace/verl_sha.txt && cd .. && \\
    rm -rf /tmp/* /var/tmp/* && pip cache purge

# The island asserts these at startup (yeto/rl/adapters/verl/pins.py).
RUN pip list > /workspace/pip_freeze_npu.txt && pip freeze >> /workspace/pip_freeze_npu.txt

CMD ["/bin/bash"]
EOF

echo "wrote $DOCKERFILE"
if [ "$PRINT_ONLY" = "1" ]; then cat "$DOCKERFILE"; exit 0; fi
if [ "$DO_BUILD" = "0" ]; then
  echo "skipping build (--no-build)."
  exit 0
fi

# The build must run on the target architecture. Cross-building this image is
# not supported here: vllm-ascend compiles custom kernels.
HOST_ARCH="$(uname -m)"
if [ "$HOST_ARCH" != "$ARCH" ]; then
  echo "error: host is $HOST_ARCH but --arch is $ARCH." >&2
  echo "       Build on the 910B4 node itself (or on a machine of the same" >&2
  echo "       architecture); vllm-ascend compiles custom kernels." >&2
  exit 3
fi

echo "building $TAG from $DOCKERFILE (SOC=$SOC, arch=$ARCH)"
docker build --build-arg "SOC_VERSION=$SOC" -t "$TAG" -f "$DOCKERFILE" "$OUT_DIR"
# Record what was built: digest plus the in-image pip freeze (task 3.11).
docker image inspect "$TAG" --format '{{json .Id}}{{"\n"}}{{json .RepoDigests}}'
docker run --rm "$TAG" cat /workspace/pip_freeze_npu.txt > "$OUT_DIR/pip_freeze_npu.txt"
echo "pip freeze saved to $OUT_DIR/pip_freeze_npu.txt"
echo "NOTE: do not push this image anywhere without asking the user first."
