#!/usr/bin/env python3
"""Regenerate the README's supported-models table from yeto/models.py.

Usage: python3 scripts/gen_model_table.py   (rewrites README.md in place)
A test (tests/test_models.py) fails when the table drifts from the source.
"""

from __future__ import annotations

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))
from yeto.models import MODEL_ALIASES, MODEL_SPECS, MODEL_WEIGHT_GB  # noqa: E402

SECTION_START = "## Supported models"
SECTION_END = "## Docs"


def table() -> str:
    rows = ["| alias | Hugging Face id | min island VRAM (GB) |", "|---|---|---|"]
    for alias, hf in MODEL_ALIASES.items():
        gb = MODEL_WEIGHT_GB.get(alias)
        size = f"{gb:g}" if gb is not None else "(Hub)"
        rows.append(f"| `{alias}` | `{hf}` | {size} |")
    return "\n".join(rows)


def component_aliases() -> str:
    rows = []
    for alias, spec in MODEL_SPECS.items():
        launch = f"--task {spec.task}"
        if spec.component:
            launch += f" --component {spec.component}"
        bits = [f"`{alias}` expands to `{launch}`"]
        defaults = []
        if spec.component_config:
            defaults.append(f"default config `{spec.component_config}`")
        if spec.adapter:
            defaults.append(f"default adapter `{spec.adapter}`")
        if spec.lora_targets:
            defaults.append(f"default LoRA targets `{spec.lora_targets}`")
        if defaults:
            bits.append("; ".join(defaults))
        if spec.base_checkpoint_env or spec.component_root_env or spec.learner_image_env:
            envs = ", ".join(
                f"`{name}`"
                for name in (
                    spec.base_checkpoint_env,
                    spec.component_root_env,
                    spec.learner_image_env,
                )
                if name
            )
            bits.append(f"runtime paths/images may be supplied by {envs}")
        rows.append("- " + "; ".join(bits) + ".")
    return "\n".join(rows) if rows else "- None yet."


def section() -> str:
    return f"""{SECTION_START}

Aliases are sugar over `yeto/models.py` (this section is generated by
`scripts/gen_model_table.py`; tests keep it in sync).

### Language-model aliases

"Min island VRAM" is the frozen-base footprint an island's GPUs must jointly
hold (bf16 base, LoRA) — add ~8 GB per GPU for activations/overhead, ×8 for
full tuning; "(Hub)" means the size is resolved from safetensors metadata at
plan time. These aliases use the default `lm` backend and support `yeto shape`
/ `--budget` auto-fleet planning.

{table()}

### Component aliases

Component aliases select a non-LM backend and component defaults. They are not
Hugging Face model ids, are not included in `yeto shape` yet, and require an
explicit `--gpu` fleet plus the runtime/checkpoint inputs expected by the
component.

{component_aliases()}

"""


def main() -> None:
    readme = pathlib.Path(__file__).resolve().parents[1] / "README.md"
    text = readme.read_text()
    start = text.index(SECTION_START)
    end = text.index(SECTION_END)
    readme.write_text(text[:start] + section() + text[end:])
    print(f"rewrote {readme}")


if __name__ == "__main__":
    main()
