#!/usr/bin/env python3
"""Regenerate the README's supported-models table from yeto/models.py.

Usage: python3 scripts/gen_model_table.py   (rewrites README.md in place)
A test (tests/test_models.py) fails when the table drifts from the source.
"""

from __future__ import annotations

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))
from yeto.models import MODEL_ALIASES, MODEL_WEIGHT_GB  # noqa: E402

SECTION_START = "## Supported models"
SECTION_END = "## Docs"


def table() -> str:
    rows = ["| alias | Hugging Face id | min island VRAM (GB) |", "|---|---|---|"]
    for alias, hf in MODEL_ALIASES.items():
        gb = MODEL_WEIGHT_GB.get(alias)
        size = f"{gb:g}" if gb is not None else "(Hub)"
        rows.append(f"| `{alias}` | `{hf}` | {size} |")
    return "\n".join(rows)


def section() -> str:
    return f"""{SECTION_START}

Aliases are sugar over `yeto/models.py` (this table is generated by
`scripts/gen_model_table.py`; a test keeps them in sync). "Min island VRAM"
is the frozen-base footprint an island's GPUs must jointly hold (bf16 base,
LoRA) — add ~8 GB per GPU for activations/overhead, ×8 for full tuning,
×0.53/×0.28 for a published fp8/fp4 base variant (`--base-dtype`); "(Hub)"
means the size is resolved from safetensors metadata at plan time.

{table()}

"""


def main() -> None:
    readme = pathlib.Path(__file__).resolve().parents[1] / "README.md"
    text = readme.read_text()
    start = text.index(SECTION_START)
    end = text.index(SECTION_END)
    readme.write_text(text[:start] + section() + text[end:])
    print(f"rewrote {readme}")


if __name__ == "__main__":
    main()
