"""``RolloutPool`` over upstream InferenceController + RolloutExecutor (task 3.2).

``generate`` runs one upstream training rollout (``prepare_rollout`` then
``rollout_executor.get``) and returns a :class:`RolloutBatchHandle` whose
``payload`` is upstream's ``RolloutDataPack`` (object-store refs; never
dereferenced here). The yeto-visible metadata comes from
:mod:`.rollout_meta_hook`, extracted in the rollout process and delivered via
a small sink. ``require_policy_tokens`` implements the pre-training identity
check (spec: mismatching groups are rejected before training).
"""

from __future__ import annotations

import json
import math
import time
from collections.abc import Callable
from pathlib import Path
from typing import Any, Protocol

from ..ports import GroupMetadata, RolloutBatchHandle
from . import LoopRunner
from .rollout_meta_hook import (
    DEFAULT_SINK_ACTOR,
    METADATA_SCHEMA,
    ROUND_META_SCHEMA,
    put_policy_token,
)


class RolloutMetadataError(RuntimeError):
    """Rollout metadata is missing, malformed or inconsistent with the batch."""


class PolicyTokenMismatch(RuntimeError):
    """Some groups were generated by a policy other than the expected snapshot."""

    def __init__(self, expected: str, groups: tuple[GroupMetadata, ...]) -> None:
        detail = ", ".join(f"{g.group_id}={g.policy_token!r}" for g in groups)
        super().__init__(f"policy token mismatch (expected {expected!r}): {detail}")
        self.expected = expected
        self.groups = groups


def policy_token(rollout_id: int, policy_hash: str) -> str:
    """yeto's policy token (design D3), carried as SGLang weight version.

    Single definition: :attr:`yeto.rl.core.PolicySnapshot.token`.
    """

    from yeto.rl.core import policy_snapshot_token

    return policy_snapshot_token(rollout_id, policy_hash)


def member_id(cell_id: Any) -> str:
    return f"engine:{cell_id}"


async def running_members(controller: Any) -> frozenset[str]:
    """Rollout members = cells the controller reports ``Running``.

    Shared by ``MilesRolloutPool.members`` and ``MilesPublisher`` so both
    sides of the driver's acknowledgement check use one source.
    """

    statuses = await controller.get_cell_statuses() or {}
    return frozenset(
        member_id(cell_id)
        for cell_id, status in statuses.items()
        if getattr(status, "phase", None) == "Running"
    )


def require_policy_tokens(batch: RolloutBatchHandle, expected_token: str) -> None:
    bad = batch.mismatched_groups(expected_token)
    if bad:
        raise PolicyTokenMismatch(expected_token, bad)


class MetadataSource(Protocol):
    def take(self, rollout_id: int) -> dict[str, Any]: ...


# --------------------------------------------------------------------------
# Sinks readable from the driver
# --------------------------------------------------------------------------


class DirMetadataSource:
    """Reads the ``dir:`` sink; the file is consumed (deleted) once read."""

    def __init__(self, directory: str | Path) -> None:
        self.directory = Path(directory)

    @property
    def sink_spec(self) -> str:
        return f"dir:{self.directory}"

    def set_policy_token(self, token: str) -> None:
        put_policy_token(token, self.sink_spec)

    def take(self, rollout_id: int) -> dict[str, Any]:
        for name in (f"rollout-{rollout_id}.json", "rollout-latest.json"):
            path = self.directory / name
            if path.exists():
                payload = json.loads(path.read_text(encoding="utf-8"))
                path.unlink()
                extra = []
                round_path = self.directory / f"round-{rollout_id}.json"
                if round_path.exists():
                    extra.append(json.loads(round_path.read_text(encoding="utf-8")))
                    round_path.unlink()
                return merge_round_metadata(payload, extra, rollout_id)
        raise RolloutMetadataError(f"no rollout metadata for rollout {rollout_id} in {self.directory}")


def merge_round_metadata(
    payload: dict[str, Any], records: list[dict[str, Any]], rollout_id: int
) -> dict[str, Any]:
    """Attach per-round counters reported after the all-samples hook (same rollout only)."""

    merged = dict(payload)
    for record in records:
        if record.get("rollout_id") != rollout_id:
            raise RolloutMetadataError(
                f"per-round metadata for rollout {record.get('rollout_id')} "
                f"arrived with rollout {rollout_id}"
            )
        for key, value in record.items():
            if key in ("schema", "rollout_id"):
                continue
            if key in merged:
                raise RolloutMetadataError(f"per-round metadata {key} reported twice")
            merged[key] = value
    return merged


def _sink_actor_class():
    import ray

    @ray.remote(num_cpus=0)
    class _YetoRolloutMetaSink:
        def __init__(self) -> None:
            self._pending: list[str] = []
            self._token: str | None = None

        def set_token(self, token: str) -> None:
            self._token = token

        def get_token(self) -> str | None:
            return self._token

        def put(self, encoded: str) -> None:
            self._pending.append(encoded)

        def take_all(self) -> list[str]:
            items, self._pending = self._pending, []
            return items

    return _YetoRolloutMetaSink


class RayMetadataSink:
    """Named Ray actor that rollout-process hooks push metadata into."""

    def __init__(self, name: str = DEFAULT_SINK_ACTOR, *, timeout_s: float = 30.0) -> None:
        import ray

        self.name = name
        self.timeout_s = timeout_s
        self._ray = ray
        self._actor = _sink_actor_class().options(name=name, get_if_exists=True).remote()

    @property
    def sink_spec(self) -> str:
        return f"ray:{self.name}"

    def set_policy_token(self, token: str) -> None:
        self._ray.get(self._actor.set_token.remote(token))

    def take(self, rollout_id: int) -> dict[str, Any]:
        deadline = time.monotonic() + self.timeout_s
        while True:
            items = [json.loads(i) for i in self._ray.get(self._actor.take_all.remote())]
            main = [i for i in items if i.get("schema") != ROUND_META_SCHEMA]
            extra = [i for i in items if i.get("schema") == ROUND_META_SCHEMA]
            if items:
                if len(main) != 1:
                    raise RolloutMetadataError(
                        f"expected one metadata record for rollout {rollout_id}, got {len(main)}"
                    )
                return merge_round_metadata(main[0], extra, rollout_id)
            if time.monotonic() > deadline:
                raise RolloutMetadataError(f"no rollout metadata for rollout {rollout_id}")
            time.sleep(0.05)


# --------------------------------------------------------------------------
# Handle construction
# --------------------------------------------------------------------------


def _number(value: Any) -> float:
    return math.nan if value is None else float(value)


def handle_from_metadata(
    payload: dict[str, Any],
    *,
    rollout_id: int,
    policy_version: int,
    policy_hash: str,
    data_pack: Any,
) -> RolloutBatchHandle:
    if not isinstance(payload, dict) or payload.get("schema") != METADATA_SCHEMA:
        raise RolloutMetadataError(f"malformed rollout metadata: {payload!r:.200}")
    reported = payload.get("rollout_id")
    if reported is not None and reported != rollout_id:
        raise RolloutMetadataError(f"metadata is for rollout {reported}, expected {rollout_id}")
    groups = tuple(
        GroupMetadata(
            group_id=str(g["group_id"]),
            sample_ids=tuple(str(s) for s in g["sample_ids"]),
            policy_token=str(g["policy_token"]),
            reward_mean=_number(g["reward_mean"]),
            reward_std=_number(g["reward_std"]),
            token_count=int(g["token_count"]),
            filtered_samples=(
                int(g["filtered_samples"]) if g.get("filtered_samples") is not None else None
            ),
        )
        for g in payload["groups"]
    )
    if not groups:
        raise RolloutMetadataError(f"rollout {rollout_id} produced no trained groups")
    indices = getattr(data_pack, "sample_indices", None)
    if indices is not None:
        expected = sorted(int(i) for i in payload.get("trained_sample_indices", ()))
        if sorted(int(i) for i in indices) != expected:
            raise RolloutMetadataError(
                f"rollout {rollout_id}: metadata samples do not match the training batch"
            )
    return RolloutBatchHandle(
        rollout_id=rollout_id,
        policy_version=policy_version,
        policy_hash=policy_hash,
        groups=groups,
        completed=int(payload["completed"]),
        aborted=int(payload["aborted"]),
        payload=data_pack,
        # rollout_meta_hook: trained-group filter drops (terminal). Carried-over
        # leftovers are not tracked until 3.6/4.1 audit the Miles buffer.
        filtered=int(payload["filtered"]) if "filtered" in payload else None,
        carried_over=None,
        tool_wait_seconds=(
            float(payload["tool_wait_seconds"]) if "tool_wait_seconds" in payload else None
        ),
        nonzero_advantages=(
            int(payload["nonzero_advantages"]) if "nonzero_advantages" in payload else None
        ),
    )


def _http_get_json(url: str, timeout_s: float = 2.0) -> Any:
    import urllib.request

    with urllib.request.urlopen(url, timeout=timeout_s) as response:  # noqa: S310 - router URL
        return json.loads(response.read().decode("utf-8"))


class MilesRolloutPool:
    """``RolloutPool`` port. ``expected_policy`` returns the published (version, hash)."""

    def __init__(
        self,
        *,
        inference_controller: Any,
        rollout_executor: Any,
        metadata: MetadataSource,
        expected_policy: Callable[[], tuple[int, str]],
        runner: LoopRunner | None = None,
        args: Any = None,
    ) -> None:
        self._args = args
        self._controller = inference_controller
        self._executor = rollout_executor
        self._metadata = metadata
        self._expected_policy = expected_policy
        self._run = (runner or LoopRunner()).run

    def generate(self, rollout_id: int) -> RolloutBatchHandle:
        policy_version, policy_hash = self._expected_policy()
        setter = getattr(self._metadata, "set_policy_token", None)
        if setter is not None:  # rollout-side group-reuse filter reads it
            setter(policy_token(policy_version, policy_hash))
        self._run(self._controller.prepare_rollout(rollout_id))
        data_pack = self._run(self._executor.get(rollout_id))
        self._offload_after_rollout()
        try:
            payload = self._metadata.take(rollout_id)
            return handle_from_metadata(
                payload,
                rollout_id=rollout_id,
                policy_version=policy_version,
                policy_hash=policy_hash,
                data_pack=data_pack,
            )
        except BaseException:
            _release(data_pack)
            raise

    def load_sample(self, *, http_get: Callable[[str], Any] | None = None) -> dict[str, int] | None:
        """rl-infra-spec 1.7: engine in-flight counts from the fork-M3 router.

        ``GET /worker_inflight`` -> ``{"inflight": {worker_url: n}, "cordoned": [...]}``.
        None when the router address is unknown or the router lacks the
        endpoint (stock Miles without M3): unknown, never reported as 0.
        """
        args = self._args
        ip = getattr(args, "sglang_router_ip", None)
        port = getattr(args, "sglang_router_port", None)
        if not ip or not port:
            return None
        try:
            data = (http_get or _http_get_json)(f"http://{ip}:{port}/worker_inflight")
        except Exception:  # noqa: BLE001 - observation only; absent endpoint = unknown
            return None
        inflight = data.get("inflight") if isinstance(data, dict) else None
        if not isinstance(inflight, dict):
            return None
        return {
            "active_requests": int(sum(int(v) for v in inflight.values())),
            "workers": len(inflight),
            "cordoned": len(data.get("cordoned") or ()),
        }

    def _offload_after_rollout(self) -> None:
        """Upstream ``train.py`` serial colocated branch (--offload-rollout)."""

        args = self._args
        if args is None or not getattr(args, "offload_rollout", False):
            return
        if getattr(args, "colocate_memory_peak_device", None) == "gpu":
            self._run(self._controller.offload_kv())
            return
        from sglang.srt.constants import (
            GPU_MEMORY_TYPE_CUDA_GRAPH,
            GPU_MEMORY_TYPE_KV_CACHE,
            GPU_MEMORY_TYPE_WEIGHTS,
        )

        level = str(getattr(args, "offload_rollout_level", "") or "")
        tags = [GPU_MEMORY_TYPE_CUDA_GRAPH]
        if "kv_cache" in level:
            tags.append(GPU_MEMORY_TYPE_KV_CACHE)
        if "weight" in level:
            tags.append(GPU_MEMORY_TYPE_WEIGHTS)
        self._run(self._controller.offload(tags=tags))

    def abort(self) -> None:
        self._run(self._controller.abort_all())

    def members(self) -> frozenset[str]:
        return self._run(running_members(self._controller))


def _release(data_pack: Any) -> None:
    try:
        from miles.utils.data import remove_rollout_data_refs
    except ImportError:  # pragma: no cover - only without miles (tests)
        return
    remove_rollout_data_refs(None, data_pack)
